### ISSUE TITLE
Rule violation does not occur at runtime

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#741] opened 2018-01-17 10:08 UTC
I used Ampersand-v3.9.0 [development:1f4819b*] to compile the following script:

```
CONTEXT Try54

PATTERN Twovalued
RULE twovalued : I[Position] = "valid" \/ "invalid"
VIOLATION (SRC I, TXT " is not a Position. Please pick 'valid' or 'invalid'.")
ENDPATTERN

POPULATION Position CONTAINS [ "valid", "invalid" ]

INTERFACE Twovalued : "_SESSION"
BOX [ probeer : V[SESSION*Position] ]
ENDCONTEXT
```

I expected that it is impossible to get other values than ``valid`` or ``invalid`` in the concept ``Position``.
Instead, I can insert other values in the concept ``Position`` through the user interface.

To reproduce, follow these steps:
1. Compile the script and generate a prototype
2. Run the prototype
3. insert the value ``misschien`` in the user interface
4. watch the atom ``misschien`` as element of ``Position`` and notice the absence of a red message.

Here is a screenshot
![afbeelding](https://user-images.githubusercontent.com/275768/35036901-1bb4b858-fb76-11e7-9697-728dd44210d2.png)

Remark: I cannot get this error at compile time. It is a runtime bug.

**Comment by Michiel-s** [comment] 2018-01-17 19:16
I just diagnosed the bug. Yes it is indeed a run-time bug, but caused by a wrong/missing specification in the generated files (generics/concepts.json).

The generated defintion for the concept `Position` is:
```json
{
        "specializations": [],
        "largestConcept": "Position",
        "affectedConjuncts": [],
        "id": "Position",
        "type": "OBJECT",
        "conceptTable": {
            "name": "Position",
            "cols": [
                "Position"
            ]
        },
        "label": "Position",
        "generalizations": [],
        "defaultViewId": null,
        "interfaces": []
    },
```
Here you can see that the aspect `affectedConjuncts` is an empty array. However, this MUST contain the 2 conjunct ids for the rule `RULE twovalued : I[Position] = "valid" \/ "invalid"`

Other concepts do have affectedConjuncts specified. I don't know why this is missing for the Position concept.

After I manually added the two relevant conjunct the invariant violation is shown and prevents the transaction from being committed.
```json
"affectedConjuncts": ["conj_0", "conj_2"],
```

This is an issue for @hanjoosten I quess.

**Comment by Michiel-s** [comment] 2018-01-17 19:46
I was looking into the haskell code and have a wild ques of what's going wrong.

In ADL2FSpec.hs there is this function for determining the conjuncts per concept. It uses `relsMentionedIn` for this. I also recall some changes @hanjoosten made that removed V and I from Declaration (b6df8e4f09db99f7cb0332649194531731a72c48). 

Can it be that `I[Concept]` is not considered a relation declaration and thereby conjuncts from rules that use this expression are not considered?

```hs
fSpecAllConjsPerConcept = converse [ (conj, smaller (source r) `uni` smaller (target r)) | conj <- allConjs, r <- relsMentionedIn $ rc_conjunct conj ]
                               where smaller :: A_Concept -> [A_Concept]
                                     smaller cpt = [cpt] `uni` smallerConcepts (gens context) cpt
```

**Comment by hanjoosten** [comment] 2018-01-17 19:51
Ha! I am looking into this bug right now too. The diagnosis of @Michiel-s is spot on!

**Comment by Michiel-s** [comment] 2018-01-17 20:03
Nice!

**Comment by hanjoosten** [comment] 2018-01-18 05:09
@Michiel-s , The fix I did last night still has some problems. The only difference in the output of the files in generics is that in the fixed version, both missing conjuncts are now present. When playing around with that generated prototype, it is quite easy to run into the following bug:

![35071716-03b290d8-fbe2-11e7-9954-295c32487b44 1](https://user-images.githubusercontent.com/1159672/35081713-062c8c18-fc16-11e7-8dd2-a72523dbf8f0.png)

Could you diagnose what is going on here?

**Comment by stefjoosten** [comment] 2018-01-18 06:44
sounds good!

**Comment by hanjoosten** [comment] 2018-01-18 22:04
I talked to @Michiel-s tonight. The problems above are because the generator should disalow some CRUD operations in certain cases. Currently, the CRUD specification is too liberal. I will create a separate issue for that.

**Comment by hanjoosten** [comment] 2018-01-18 22:55
There is another problem with this same script, for which issue #746 has been created.

**Closed** 2018-01-18 23:00 UTC
Labels: bug, priority:critical
