### ISSUE TITLE
Too strict type checking in population statement

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#142] opened 2015-07-29 05:36 UTC
Consider the following scriptlet:

```
CLASSIFY Application ISA Box
RELATION boxDoc[Box*Documentation] [UNI,TOT]
```

Since every Application ISA Box, it should be allowed to assign a Documentation to any application
Here is an example of what the Excel sheet that does this, should look like

```
 [Apps&Boxes]  |     boxDoc
 ------------------------------
  Application  |  Documentation
 ------------------------------
     App1      |    App1Doc
```

However, `ampersand.exe` produces the following errormessage:

```
 No declaration for boxDoc[Application*Documentation]
```

Note: the frontend Excel Import facility (correctly) imports this file.

**Comment by hanjoosten** [comment] 2015-07-31 10:14
This is a 'feature' of the current typechecker, and has nothing to do with the excel import. Let me explain.

Consider a scriptlet like this:
```
CONTEXT Test IN DUTCH
   CLASSIFY Application ISA Box
   boxDoc :: Box * Documentation[UNI,TOT]
   POPULATION boxDoc[Application*Documentation] CONTAINS
       [("App1","App1Doc")]
ENDCONTEXT
```

This results in the same type error:
```
Reading file Issue142.adl
Error(s) found:
No declaration for boxDoc[Application*Documentation]
  Error at symbol () in file Issue142.adl at line 4 : 15
```

I agree that there should not be a type error. @sjcjoosten : Could you have a look on this one? I have added above script in the test in sentinel.

**Comment by sjcjoosten** [comment] 2015-08-10 16:12
I do not agree that the string "boxDoc[Application*Documentation]" should be interpreted as "boxDoc[Box*Documentation] /\ V[Application*Documentation]". In the current type-checker, the brackets [] are meant for disambiguation only, and since this relation does not exist, ampersand should give an error. The error message could be better, the symbol () is not in the file Issue142.adl, so it is currently a bit cryptic.

I do agree that something needs to be changed to the type-checker, since -- for this example -- we have to check that "Application ISA Box".

Could we change the excel import such that the following works? If the excel import works via the population syntax, maybe we have to change this too?

     [Apps&Boxes]  |     boxDoc[Box*Documentation]
     ------------------------------
      Application  |  Documentation
     ------------------------------
         App1      |    App1Doc

**Comment by hanjoosten** [comment] 2015-08-10 16:29
Forget about the Excel syntax. You can focus on the regular syntax, as in \shouldSucceed\Issue142.adl. If that script will pass, so will the Excell variant.

**Comment by RieksJ** [comment] 2015-08-11 06:10
The issue that is at hand here is to identify the relation in which to populate the pair (App1,App1Doc). The fact that we start to work with excel files indicates that there is a need for being more pragmatic than what is currently offered in ADL. Based on the proven practice of the ExcelImporter in the front end, I suggest the following algorithm:

     Src = 'element in 1st column, 2nd row';
     Rel = 'element in other column, 1st row'
     Tgt = 'element in other column of 2nd row';
     WHILE ('Rel[Src*Tgt]' does not identify a relation)
        if (there is no generaliazation Gen(Src) of Src) ERROR ('relation does not exist');
        Src := Gen(Src);
     ENDWHILE
     return 'Rel[Src*Tgt]';

**Comment by hanjoosten** [comment] 2015-08-11 06:23
Once again: THIS HAS NOTHING TO DO WITH EXCEL!

[Issue142.adl](https://github.com/AmpersandTarski/ampersand-models/blob/master/Tests/ShouldSucceed/Issue142.adl) has the exact same typing thing. It is in the sentinel. We get the error:

```
Running Ampersand ["--haskell"] on /home/sentinel/git/ampersand-models/Tests/ShouldSucceed/Issue142.adl. {should succeed} 
Execute: /home/sentinel/.cabal/bin/ampersand /home/sentinel/git/ampersand-models/Tests/ShouldSucceed/Issue142.adl --outputDir=/home/sentinel/git/sentinel/www/ampersand/Issue142/fSpec --haskell +RTS -M4G in /home/sentinel/git/ampersand-models/Tests/ShouldSucceed 
Execution failure:
Exit code 10 
stdout: 
Error(s) found: 
No declaration for boxDoc[Application*Documentation] 
Error at symbol () in file /home/sentinel/git/ampersand-models/Tests/ShouldSucceed/Issue142.adl at line 4 : 15 
```

**Comment by Michiel-s** [comment] 2015-08-24 05:51
@sjcjoosten could you change the type-checker, so that -- for this example -- the population statement:
```
POPULATION boxDoc[Application*Documentation] CONTAINS [("App1","App1Doc")]
```
is valid in script:
```
CONTEXT Test IN DUTCH
   CLASSIFY Application ISA Box
   boxDoc :: Box * Documentation[UNI,TOT]
   appSome :: Application * Something
   POPULATION boxDoc[Application*Documentation] CONTAINS
       [("App1","App1Doc")]
ENDCONTEXT
```
As you already mentioned, the typechecker should anticipate for ISA statements. 

Interpreting `boxDoc[Application*Documentation]` as `boxDoc[Box*Documentation] /\ V[Application*Documentation]` is not needed. In both the excelimporter as the population statements we always know the concept of the src and tgt atom. However, the problem lies in mixing relations from specialization and generalization concepts in one line. e.g.:

[Apps] | boxDoc | appSome
Application  |  Documentation | Something
-----------------------------------------------------
App1 | App1Doc | Some1

I agree with you that it is also a possibility to specify boxDoc[Box*Documentation] instead of just boxDoc in the first row, but that's more verbose and the **php** excel importer (not the haskell one mentioned above) can also deal with using relations of generalization concepts.

**Comment by sjcjoosten** [comment] 2015-08-24 09:29
No I cannot. I do not agree that the proposed script is correct: the brackets [] are for disambiguation purposes only, not for type-casting. Please propose a syntax (without []) for the POPULATION statement in which type casting is possible, I can make sure it gets through the type-checker.

**Comment by Michiel-s** [comment] 2015-08-24 09:40
Ah, now I understand. @hanjoosten, than it is the excelimporter after all, because the excel lines should be rewritten to `POPULATION boxDoc CONTAINS [("App1","App1Doc")]`, without the disambiguation brackets[] or specified with the correct types to make correct use of the type checker.

**Comment by hanjoosten** [comment] 2015-08-24 11:34
No, I cannot either. The Excel importer does not know about types at all!. It does a simple translation. If you fill in the concept name (it is optional!), then and only then the brackets are added and sent to the type-checker. So if you do not want that, you can leave out the Concept name, exactly the same as if you would leave it out in a script. 

If in Excell you have:

[Apps] | boxDoc 
---------|---------------------
Application  |  Documentation 
App1    |     App1Doc       
 
then this will translate to
```
POPULATION boxDoc[Application*Documentation]
   CONTAINS [ ("App1" , "App1Doc") ]
```
However, if you would write

[Apps] | boxDoc 
---------|---------------------
Application  |  Documentation 
App1    |     <empty>       

then that would translate to
```
POPULATION boxDoc
   CONTAINS [ ("App1" , "App1Doc") ]
```

**Comment by hanjoosten** [comment] 2015-08-24 12:06
Update: Ik heb zojuist mer Bas gesproken. Conclusie is dat het inderdaad niet kan, maar dat we het toch gaan doen. 

We doen dat door een aanpassing te maken in de P-Structuur in Haskell. (P_Population wordt uitgebreid). Hiermee kan de disambiguator extra informatie krijgen. Die informatie gaan we niet aanleveren vanuit de 'gewone' ADL-parser, maar wél vanuit de Excel-parser. 
Bas hoopt/verwacht hier over ca. anderhalve week aan toe te komen. Daarna moet ik nog iets doen, dus verwacht een week of twee vanaf vandaag...

**Comment by stefjoosten** [comment] 2015-08-24 13:58
I agree with @sjcjoosten that the reason for rejecting this script is that the relation "boxDoc[Application*Documentation]" does not exist. Let me do some experiments in Atoms.adl, to find out whether it makes sense to introduce: 

    RELATION sources[Relation*Concept] -- meant for: sources = source;isas~
    RELATION targets[Relation*Concept] -- meant for: targets = target;isas~
    
    ROLE ExecEngine MAINTAINS isaRelInsSrc, isaRelInsTgt, isaRelDelSrc, isaRelDelTgt

    RULE isaRelInsSrc: source;isas~ |- sources
    VIOLATION (TXT "{EX} InsPair;sources;Relation;", SRC I, TXT ";Concept;", TGT I)

    RULE isaRelInsTgt: target;isas~ |- targets
    VIOLATION (TXT "{EX} InsPair;targets;Relation;", SRC I, TXT ";Concept;", TGT I)

    RULE isaRelDelSrc: sources |- source;isas~
    VIOLATION (TXT "{EX} DelPair;sources;Relation;", SRC I, TXT ";Concept;", TGT I)

    RULE isaRelDelTgt: targets |- target;isas~
    VIOLATION (TXT "{EX} DelPair;targets;Relation;", SRC I, TXT ";Concept;", TGT I)

**Comment by sjcjoosten** [comment] 2015-08-24 14:27
Still need to fix the typecheck part.

**Comment by hanjoosten** [comment] 2015-08-24 14:28
I assume you closed this by accident.

**Comment by stefjoosten** [comment] 2015-08-24 18:42
yes. It should remain open. Sorry for that. Is inexperience with Github's issues.

**Comment by sjcjoosten** [comment] 2015-08-27 15:06
I created a pull request which fails to build on travis, but I cannot reproduce on my ghc version ("cabal test" does not compile, and "cabal install"/"cabal build" both work without errors). can @hanjoosten fix this? Ideally without reverting my change to the A-structure..

**Comment by hanjoosten** [comment] 2015-08-28 06:39
Thanks @sjcjoosten , for the branch. Let me try to summarize the change:

# Summarize
The effect is on parsing / checkin population statements only. We have two separate parsers:

##  1) The parser for ADL files.
There is **no change in behaviour** in this parser.That would require extra syntax in the signature of the named relation. Iff a signature is given, that relation must be declared. So the example given by @Michiel-s earlier in this discussion:
```
CONTEXT Test IN DUTCH
   CLASSIFY Application ISA Box
   boxDoc :: Box * Documentation[UNI,TOT]
   appSome :: Application * Something
   POPULATION boxDoc[Application*Documentation] CONTAINS
       [("App1","App1Doc")]
ENDCONTEXT
```
This example will still fail, This can be solved either by:
1 remove the signuature in the population statement:
```
CONTEXT Test IN DUTCH
   CLASSIFY Application ISA Box
   boxDoc :: Box * Documentation[UNI,TOT]
   appSome :: Application * Something
   POPULATION boxDoc CONTAINS
       [("App1","App1Doc")]
ENDCONTEXT
```
2 Use the exact signature:
```
CONTEXT Test IN DUTCH
   CLASSIFY Application ISA Box
   boxDoc :: Box * Documentation[UNI,TOT]
   appSome :: Application * Something
   POPULATION boxDoc[Box*Documentation] CONTAINS
       [("App1","App1Doc")]
ENDCONTEXT
```

##  2) The parser for .xlsx files (AKA Excell importer)
In the Excell importer, for convenience reasons, a Concept may be specified that is equal or more specific than the concept of the (source/target) of the specified relation. However, take note that the  atoms are still populated in the original relation, it is **not** inferred/assumed that the atoms are element of the more specific concept. So in the previous given example:

[Apps] | boxDoc 
---------|---------------------
Application  |  Documentation 
App1    |     App1Doc       
 
now this will be handled exactly the same as
```
POPULATION boxDoc[Box*Documentation]
   CONTAINS [ ("App1" , "App1Doc") ]
```

Note, that it is not allowed to use a more **generic** concept. That will lead to an error message.

**Comment by sjcjoosten** [comment] 2015-08-28 07:57
This is spot on! Thank you for adding the test cases, there is indeed still an error in Issue142Fail. Will be fixed...

**Comment by sjcjoosten** [comment] 2015-08-28 08:33
Should be fixed now (Sentinel is running to confirm)

**Comment by hanjoosten** [comment] 2015-08-28 08:43
Top! Sentinel is nu tevreden over deze fix. En ik ook! Je mag de pull zelf uitvoeren, als je wilt

**Comment by Michiel-s** [comment] 2015-08-28 14:33
Bedankt mannen! Het werkt.

**Comment by stefjoosten** [comment] 2016-12-14 07:07
For some reason yet unknown, this issue has re-occured in Travis' job #2181.1.
Check it out on https://travis-ci.org/AmpersandTarski/Ampersand/jobs/183825390

**Comment by stefjoosten** [comment] 2016-12-15 07:29
Fixed

**Closed by stefjoosten** 2016-12-15 07:29 UTC
Labels: bug, component:type checker, priority:high
