### ISSUE TITLE
More specific message requested for `!fatal error 54`

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#335] opened 2016-03-20 14:41 UTC
In a rather large script, I came across the following message

     ampersand.exe: !fatal, called at src\Database\Design\Ampersand\ADL1\P2A_Converters.hs:63:17 in main:Database.Design.Ampersand.ADL1.P2A_Converters
                  Ampersand v3.4.0[branch_#228:890de97]
                  error nr: 54
       A concept turned out to be a built-in type.

It would help the user to find where the error occurred if the message would actually specify the concept that turned out to be a built-in type.

**Comment by RieksJ** [comment] 2016-03-20 15:11
Here is a script that you can use to reproduce this behaviour. It also shows that it is a bug.

     CONTEXT Issue335 IN ENGLISH
     
     r :: A * B [UNI,TOT]  REPRESENT B TYPE BIGALPHANUMERIC
     s :: A * C [UNI]      REPRESENT C TYPE BIGALPHANUMERIC
     
     RULE "Initialize s": (I[A]-(s;s~));r |- s
     
     ENDCONTEXT

**Comment by hanjoosten** [comment] 2016-03-20 21:32
Rieks, please only upload testscripts to ampersand/testing/travis if the script is proven to succeed. A script like the one above does not fit that criterium. It shows the presence of a bug. Scripts like this must go into ampersand/testing/sentinel. Only once the bug is fixed, and the script proves to be handled correctly, the script may be moved into the travis directory as a regression test. 
Could you please move this test accordingly?

**Comment by hanjoosten** [comment] 2016-03-20 22:52
Fatal messages are not supposed to happen, and hence are not ment to be understood by users. For the developers, there is enough information in the error message. Together with a testcase, as you have given above, it should be possible to fix it. Until then, if the testcase is put in the sentinel directory, it will be signaled to the developer team.

**Comment by RieksJ** [comment] 2016-03-21 14:12
Since I'm getting more of this error as I'm converting stuff to the new branch_#228, I've set a prioritylevel. @stefjoosten: could you verify that Han is the right person to deal with this, and re-assign if not?

**Comment by hanjoosten** [comment] 2016-03-22 15:18
This is a bug in the typecasting stuff @sjcjoosten  introduced last December. I Hope he can have a look at it.

**Comment by sjcjoosten** [comment] 2016-03-22 22:16
Will take a look at this during easter. Not sure whether the script is correct, but I fully agree that this is a bug, per Han's reasoning.

**Comment by sjcjoosten** [comment] 2016-03-24 13:49
Is it really a problem when a branch does not pass? Does this bug occur in master too?

**Comment by sjcjoosten** [comment] 2016-03-24 15:41
The commit https://github.com/AmpersandTarski/ampersand/commit/f59329e6b624c0e15e290900d9a62f1bcf2831bb caused this issue in the branch, which makes me suspect that this issue is also in Master.

Question: where should the issue be fixed, in the branch or in the master? I only want to fix this issue once, and by that I mean that whoever created the branch will take care of future merge conflicts. I feel like I should fix this issue in (a new branch from the) master, and not in a branch that is not intended for this issue (judging by its name).

PS: Here's some background on how I found the bug:
- obtain more information on where the bug arises: add "import GHC.Stack" to the list of imports, "ImplicitParams" as a LANGUAGE pragma, and "(?loc :: CallStack) =>" to the function in which the fatal occured (mustBeConceptBecauseMath). Note: this was a bit counter-intuitive since "fatalV" was locally defined and did not have its own type signature, so I had to add "fatalV :: (?loc :: CallStack) => a".
- I iterated the above process until I found the culprit. It is "castSign :: Type -> Type -> Signature". Its type tells me that it should provide a (A_Concept) Signature with no room for throwing an error, which is not possible if one of the first two arguments is not an A_Concept. Consequently, I changed the type of castSign to "castSign :: A_Concept -> A_Concept -> Signature". Type checker will then tell me what else I should change.

**Comment by sjcjoosten** [comment] 2016-03-24 15:47
Here is a smaller script that triggers the bug:

```
CONTEXT Issue335 IN ENGLISH

REPRESENT B TYPE BIGALPHANUMERIC
REPRESENT C TYPE BIGALPHANUMERIC

RULE "Initialize s": I[B] |- I[C]

ENDCONTEXT
```

**Comment by sjcjoosten** [comment] 2016-03-24 17:53
Closing this since it is fixed in the branch the issue was reported in.. feel free to reopen (as usual)

**Closed by sjcjoosten** 2016-03-24 17:53 UTC
Labels: bug, component:global, priority:high

**Comment by RieksJ** [comment] 2016-03-25 04:42
@sjcjoosten Thanks a lot!
