### ISSUE TITLE
Runtime error: Infinite loop in INTERFACE referencing

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#37] opened 2015-03-06 08:20 UTC
It seems that if you use refer to `INTERFACE Kabels` at multiple places (in other `INTERFACE`s), you get the (runtime!) error:

     Error! 500 Internal Server Error: Infinite loop in interface 'Kabels' by referencing 'Kabels'

An example of this can be found in the repo `ampersand-models\NewFrontend\RWS\RWSbug.adl`

A workaround for this is to use the actual contents of the referenced `INTERFACE`s at all (but one) place rather than to refer to them.

**Comment by Oblosys** [comment] 2015-03-06 10:09
This is a duplicate of #29. Another workaround is to replace labels "Kabels" and "Installaties" in "Overzicht" by names that are not interface labels.

**Closed by Oblosys** 2015-03-06 10:09 UTC
Labels: bug, component:front-end, component:prototype generator, priority:low
