### ISSUE TITLE
Feature request for enhanced testing of prototype framework existence/loading 

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#948] opened 2019-05-03 10:47 UTC
It sometimes happens, particularly with novice &-users, that generation of a prototype fails and a message appears that says that some part of the prototype framework is missing, e.g. a template. 

Currently, the & prototype generator does not generate the frontend files when the prototype directory exists and is not empty. However, what it should do is test for the existence of a properly installed frontend.

This can be easily achieved by 

- checking whether or not the prototype directory exists, and if so, whether or not it contains a semaphore file, and if so, refrain from installing the frontend files. In all other cases the frontend files should be installed, optionally overwriting existing stuff.
- writing a semaphore file to the prototype directory after the frontend files are succesfully installed.

**Comment by RieksJ** [comment] 2019-06-12 09:00
I have run into this problem for a second time. The use-case is when you have opened a log file and then try to reinstall everything. If the editor did not release the log file or log directory, the stuff does not all get removed (which is not all that bad, unless of course this results in templates not being copied into the htdocs directory).

**Comment by Michiel-s** [comment] 2019-07-20 13:03
I think this inconvenience is caused by your own bat scripts. When you generate a prototype and use the switch/config `—reinstall-prototype-framework` the Ampersand executable tries to empty the target folder. If it can’t do so because a file it in use, the process fails and a error is returned. You should act on that error. I’m not sure, but maybe your bat script continues and you won’t notice the error.
The next time you generate to this folder, without the reinstall switch/config, you run into the error that the prototype framework is not complete.

**Comment by Michiel-s** [comment] 2020-08-09 17:10
I’m closing this issue because we will implement #1093. When the new prototype workflow is implemented, you download (or include the prototype framework) yourself, or do this with Docker. Then you use the compiler to generate some files to the generics folder. The Ampersand compiler won’t be downloading nor emptying the output folder.

We don’t have the issue with incorrect/incomplete framework anymore.

**Closed by Michiel-s** 2020-08-09 17:10 UTC
Labels: component:prototype generator, enhancement, software process
