### ISSUE TITLE
Population as seen by Ampersand vs MySQL (With validateSQL)

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#342] opened 2016-03-23 08:24 UTC
In issue #166 there was an issue with the following script:

```
CONTEXT SinterklaasTest IN DUTCH

RULE toBeOrNotToBe : -'Sinterklaas'[Persoon]
MEANING "De persoon 'Sinterklaas' bestaat niet."

ENDCONTEXT
```

Issue #166 has been closed, but recently there is a discrepancy between Ampersand and SQL:

```
Initializing temporary database 
Number of expressions to be validated: 1 
Checking rule "toBeOrNotToBe": expression = 'Sinterklaas'[Persoon] 
Mismatch between SQL and Ampersand 
Origin: rule "toBeOrNotToBe", expression: 'Sinterklaas'[Persoon] 
SQL violations: 
[] 
Ampersand violations: 
[("Sinterklaas","Sinterklaas")] 

ERROR: Invalid SQL Expression 
```

Who is right, (Ampersand or SQL) and why??

**Comment by hanjoosten** [comment] 2016-04-17 21:01
@stefjoosten ? @sjcjoosten  ?

**Comment by sjcjoosten** [comment] 2016-09-27 18:38
Is this issue still occurring?

**Comment by hanjoosten** [comment] 2016-09-27 19:51
yes. see [our faithfull Sentinel](http://sentinel.tarski.nl/)

**Comment by sjcjoosten** [comment] 2016-09-27 21:25
Might the "Invalid SQL Expression" be the cause of this mismatch?
Judging from the title of Issue166, the script should be free of errors (no errors should occur in the initial population, which is empty, causing 'Sinterklaas' not to exist as demanded from the rule). In that case, there is also a bug in the Ampersand compiler.

**Comment by hanjoosten** [comment] 2016-09-29 05:39
## Symptoms 
The script currently fails, saying:

```
Mismatch between SQL and Ampersand 
Origin: rule "toBeOrNotToBe", expression: 'Sinterklaas'[Persoon] 
SQL violations: 
[] 
Ampersand violations: 
[("Sinterklaas","Sinterklaas")] 

Validation error. The following expressions failed validation: 
Origin: rule "toBeOrNotToBe", expression: 'Sinterklaas'[Persoon] 

ERROR: Invalid SQL Expression 
```
## Diagnosis
Based on issue #166 we concluded that atoms mentioned in expressions must not be automatically put into the population. Hence, `'Sinterklaas'` should NOT be in the initial population.

## Conclusions
  * I am curious why `'Sinterklaas'` shows up in the Ampersand violations. It should't
  * I am also curious that it doesn't seem to find it's way into the database, since it is in the population Ampersand uses.

**Comment by Michiel-s** [comment] 2021-11-14 13:39
I think we can close this one as we don't have any failing test anymore. Or is this issue not included in the testset. @hanjoosten Could you verify?

**Closed by Michiel-s** 2021-11-14 13:39 UTC

**Comment by stefjoosten** [comment] 2021-11-14 13:45
It is safe to close this one. I have verified "Sinterklaas" (this issue, first comment) on rap.cs.ou.nl. It compiles without errors and the prototype install causes no errors.
