### ISSUE TITLE
Typechecker logic seems wrong 

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#192] opened 2015-09-16 09:58 UTC
Consider the following script:

```
CONTEXT Issue192 IN DUTCH
INCLUDE "Issue192.xlsx"
   CLASSIFY Auto ISA Voertuig
   RELATION eigenaar [Voertuig * Persoon] [UNI,TOT]
   RELATION aantalWielen [ Auto * Aantal]  [UNI,TOT]
ENDCONTEXT
```
and the following excel sheet for the population:

![hjo 20150916 11 50 15](https://cloud.githubusercontent.com/assets/1159672/9901637/1f093f78-5c69-11e5-82d1-d0358dec1409.jpg)

This leads to the following error message:

```
Error(s) found:
The Tgt concept for the population pairs, namely Aantal 
  must be more specific or equal to that of the relation you wish to populate, namely: "Aantal" (Tgt of aantalWielen :: Auto -> Aantal)
  "Issue192.xlsx":
   Sheet: Voertuig, B1
```

This is obviously wrong! 
(I have the feeling that this somehow relates to issue #191)

**Comment by hanjoosten** [comment] 2015-09-16 10:10
The cause seems to be the fix we did about 3 weeks ago. If we would write a similar population statement in ADL, (remove the include, and add:

```
POPULATION eigenaar[Auto*Persoon] CONTAINS 
    [ ("wagen1", "Piet")
    ]
POPULATION aantalWielen[Auto*Aantal] CONTAINS
    [ ( "wagen1", "vier")]
```

In ADL, we now get an error:

    No declaration for eigenaar[Auto*Persoon]
      Error at symbol () in file Issue192.adl at line 10 : 12

**Comment by sjcjoosten** [comment] 2015-09-16 10:15
The behavior for the POPULATION statements is correct, the behavior for the excel files is not. Recall that types in the excel files are no longer a synonym for the types between [*] in POPULATION statements

**Comment by hanjoosten** [comment] 2015-09-16 10:18
I fully agree that the ADL error is correct. The error when using the Excel file behaviour is not. In my opinion It should either be fixed, or it will give us a valid argument to prohibit the excel file behaviour.

**Comment by sjcjoosten** [comment] 2015-09-16 10:24
I agree. However, I cannot reproduce this error:

```
Error(s) found:
The Tgt concept for the population pairs, namely Aantal 
  must be more specific or equal to that of the relation you wish to populate, namely: "Aantal" (Tgt of aantalWielen :: Auto -> Aantal)
  "Issue192.xlsx":
   Sheet: Voertuig, B1
```

What switches do you use to obtain it? I checked in two files that show no problem in ampersand-models

**Comment by sjcjoosten** [comment] 2015-09-16 10:41
I was able to reproduce this issue by adding a space after the field B1 ("Aantal" -> "Aantal "). I will change the error message to put quotes around the Tgt concept, i.e.:

The Tgt concept for the population pairs, namely "Aantal "

That would show the issue clearer.

**Comment by hanjoosten** [comment] 2015-09-16 10:43
Aargh! I just checked in the files in Ampersand-models. Sentinel reproduced it too. Didn't think about the spaces.

**Closed** 2015-09-16 10:44 UTC
