### ISSUE TITLE
!fatal in P2A_Converters.hs - A ISA A

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#896] opened 2019-01-25 10:59 UTC
The following script produces a fatal:
```adl
CONTEXT "Issue89x"
    CLASSIFY A ISA A
ENDCONTEXT
```

**Comment by hanjoosten** [comment] 2019-01-25 12:34
Interesting. The root cause of this issue seems the fact that we are not consistent in the use of generalisations. 

@sjcjoosten explained earlier that in fact, the statement `CLASSIFY A ISA B` is syntactical sugar for `CLASSIFY A IS A /\ B`. By definition, for all concepts we assume `CLASSIFY A IS A`, which is totally logical to do. I did some experiments. Writing `CLASSIFY A IS A` yealds no errors, while writing `CLASSIFY A IS A /\ A` gives the same error as above.

**Comment by sjcjoosten** [comment] 2019-01-25 12:45
That sounds completely consistent!

This can be fixed in the type-checker, in the same way that we ensure that the type graph is cycle-free. This is a particular instance of that. I suppose we wish to allow `A ISA A`, but make sure it doesn't propagate into the rest of Ampersand. If there's a good reason to forbid `A ISA A` then that should be straightforward too, but I cannot see one.

**Comment by stefjoosten** [comment] 2019-01-25 19:52
We have seen this before in issue #742

**Comment by sjcjoosten** [comment] 2019-07-07 09:54
Closed via d92407f

**Closed** 2019-07-07 09:54 UTC
Labels: bug
