### ISSUE TITLE
Malformed UTF-8 characters inhibit deployment of a prototype

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1184] opened 2021-06-24 06:28 UTC
# What happened
I tried to run a prototype called `ApplicatieArchitectuur`, but it failed during installation just after installing the database. I verified with phpAdmin that the database has been created and filled with the initial population.
This is the last part of the log file:
```
[2021-06-23 17:11:34] DATABASE.INFO: Commit mysql database transaction for Transaction 714450335 [] {"request_id":"8aeaf4a337","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
[2021-06-23 17:11:34] DATABASE.INFO: 21 queries executed in this transaction [] {"request_id":"8aeaf4a337","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
[2021-06-23 17:11:34] API.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] {"request_id":"8aeaf4a337","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
[2021-06-23 17:11:34] API.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded [] {"request_id":"8aeaf4a337","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
[2021-06-23 17:11:36] API.CRITICAL: Malformed UTF-8 characters, possibly incorrectly encoded [] {"request_id":"8aeaf4a337","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
[2021-06-23 17:11:36] API.CRITICAL: Malformed UTF-8 characters, possibly incorrectly encoded [] {"request_id":"8aeaf4a337","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
[2021-06-23 17:11:36] PERFORMANCE.INFO: Peak memory used: 86.14 Mb [] {"request_id":"8aeaf4a337","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
[2021-06-23 17:11:36] PERFORMANCE.INFO: Execution time  : 21.21 Sec [] {"request_id":"8aeaf4a337","ip":"172.18.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
172.18.0.2 - - [23/Jun/2021:17:11:15 +0000] "GET /api/v1/admin/installer?defaultPop=true HTTP/1.1" 500 521 "http://localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0"
127.0.0.1 - - [23/Jun/2021:17:11:36 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.15 (internal dummy connection)"
172.18.0.2 - - [23/Jun/2021:17:12:01 +0000] "-" 408 0 "-" "-"
```
# Steps to reproduce

1. I cloned Ampersand from commit 732019e3f46bd716fb1d02d84821e09c0f36d63a
2. I generated a local container using
```bash
docker build -t ampersandtarski/ampersand:local .
```
(This takes over an hour, but it does terminate successfully.)
3. I built my prototype and deployed it:
```bash
docker compose build
docker compose up -d
```
4.
In my browser (chrome) I navigated to localhost

# Screenshot / Video
<img width="1680" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/123141541-c5763100-d458-11eb-93be-1f9717af8e48.png">

**Comment by stefjoosten** [comment] 2021-06-28 06:13
# Analysis
1. The problem with the UTF8 character leads me to believe it is something I did in the compiler recently. So I'll try to find an earlier version that does not exhibit this behavior. Let me first find an earlier commit of "development" that does not exhibit this behavior.
   a. The error popped up when running a development version from commit 732019e3f46bd716fb1d02d84821e09c0f36d63a.
   b. The same error occurred when running a development version from commit 481ed2751c8df536c401c4c4ac6039660820821e, which is a merge by Han on June 5th.
   c. Finally I ran Ampersand from commit 21290a78b3405d32f99155e5e571f74164838d24, which is a merge by @hanjoosten on May 30th. Again with the same mistake.
2. Another idea is to start with the application itself. To see whether there are applications that still run with the same compiler (21290a78b3405d32f99155e5e571f74164838d24), I ran RAP/Demos/Enroll as a standalone application from AmpersandTarski/RAP@85665bcbde32d2ff70bc9727fa339e6dc5f9e4cf, by executing the following commands:
   ```bash
   cd RAP/Demos/Enroll
   docker compose build
   docker compose up -d
   ```
   This works fine as shown in this screenshot:
   <img width="691" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/123210890-f8eda580-d4c2-11eb-82f7-8035a1db517a.png">
   So it seems plausible to go to the application
3. So where do the malformed UTF-8 characters come from?
   I checked the include tree. It consists of 4 .adl-files only. There are no spreadsheets
From these runs, I conclude that I will have to look into the application more closely.
To be continued...

**Comment by stefjoosten** [comment] 2021-07-09 08:14
# Diagnosis
I inspected the content of concept `Functionaliteit` in file `Pop20210518.adl` and found that these are longer strings. So I tried the following fix:
```Ampersand
REPRESENT Functionaliteit TYPE BIGALPHANUMERIC
```
This helped. The application works now.

# Structural solution
Problem solved, issue closed? Don't think so! I've spent over a day to get this diagnosis, and that is frustrating for a stupid error like this. This error could have been caught in the compiler (something like checking on the length of strings in view of the technical type). It could have been caught in the back-end (something like checking the JSON-file that atoms match the technical type). This thing "fell through" to the level of the database and gave error messages that are extremely laborious to fix. @hanjoosten @michiel, your opinions please...

**Comment by hanjoosten** [comment] 2021-07-09 08:27
Nice catch. In the past we had that database refuse to insert text that is too long. That is a database setting, and I think that should be in place by default. I suspect that that setting is no longer there for some reason, because then you would presumabley have gotten some other error message. 
At compiletime we could do similar tests. That could lead to at least warnings.

- [ ] Can you check these settings?
- [ ] Implement warnings for population of ALPHANUMERIC that is too long for the current database (MySQL).

**Comment by Michiel-s** [comment] 2021-11-13 15:54
The issue described with too long chars and checking that compile time for default population is a duplicate of #1199 

Let's close the issue here.

**Closed by Michiel-s** 2021-11-13 15:54 UTC
Labels: priority:normal, bug, under analysis
