### ISSUE TITLE
Trailing whitespace is not treated right in the database

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#263] opened 2016-01-06 10:32 UTC
This issue is visible by executing the prototype ampersand-models/Blik/Arch.adl in of commit AmpersandTarski/ampersand-models@142cac661df8e3855f3c6f5552c36b1fc69fb202, which has been compiled with Ampersand v3.1.0[master:ac300ab], build time: 05-Oct-15.

When the user resets the database (from his browser), the following error 500 occurs:

```
Error! 500 Internal Server Error: Duplicate entry 'Import ' for key 'PRIMARY' in query:INSERT INTO "Tekst"
```

This occurs in `Generics.php`.
# Analysis

The problem seems to be that Ampersand distinguishes between the atoms `'Import'` and  `'Import '`, while SQL treats them as equal. The error message goes away by post-editing the phrase `INSERT INTO "Tekst"` and substituting it by `INSERT IGNORE INTO "Tekst"`. This does not solve the problem, however. It is a surrendering to SQL's definition of equality.
# Screenshot of the error

![image](https://cloud.githubusercontent.com/assets/275768/12140489/ab631f5a-b468-11e5-8e19-56bd22961848.png)

**Comment by hanjoosten** [comment] 2016-01-06 16:13
See also [this thread](http://stackoverflow.com/questions/12542889/mysql-5-5-losing-trailing-spaces-in-query) about trailing spaces in MySQL.

**Comment by hanjoosten** [comment] 2016-03-14 09:13
There is a dillemma with this, as long as we use a database like MySQL:
MySQL trims trailing whitespace BY DESIGN. If we do not want that feature, we can disable it by using BINARY. However, then no indexing can be used, which will eventually lead to bad performance. 

What do we want? I think trimming the trailing spaces from atoms will be OK for 99.99% of the cases. The performance penelty will be much more harmfull in the long run. So let's trim the trailing spaces.

@stefjoosten please confirm.

**Comment by Michiel-s** [comment] 2016-03-14 13:02
I vote for trailing whitespace. The BINARY option has more disadvantages.

**Comment by RieksJ** [comment] 2016-03-14 14:27
I would like to see a workaround for cases where trailing whitespace is specifically necessary. One example is the UETP case where criteria texts are split into phrases and variablenames, and for the  (future) construction of texts that are criteria with values inserted, it is necessary to know where the whitespaces are.
Would it be possible to REPRESENT such phrases as TYPE BINARY?

**Comment by WolframKahl** [comment] 2016-03-14 17:16
A standard work-around would be using some kind of escape sequence, and systematically escaping and un-escaping at the database interface.
(URLs also cannot contain spaces.)

What is the current string interface to MySQL? (ASCII, ISO-Latin-1, Unicode, UTF-8, ...?)

**Comment by RieksJ** [comment] 2016-03-15 05:17
Another way to 'solve' this problem is to forbid the use of surrounding whitespace for object-type atom identifiers (dirty identifiers) and produce a warning- or error message. That will alert the user rather than reverting to 'smart' behaviour that may not always be appropriate.

But if we want to be smart, then, since this seems to be a SQL internal matter, I support solutions that have knowledge about the internal stuff we work. I then suggest to trim whitespace from 'object'-atoms, but not for 'alphanumeric' or 'bigalphanumeric', as they contain texts that are meant to be texts. If you want to compare texts, then (leading/trailing) spaces should count.

**Comment by hanjoosten** [comment] 2016-03-15 06:33
Well, as long as there is no consensus on what we want, let's do nothing until we know what we want.

**Comment by Michiel-s** [comment] 2019-02-05 20:39
This has to do with the collation of the charset for a column/table/database/connection.
Currently we specify for tables `CHARACTER SET UTF8 COLLATE UTF8_BIN`
The UFT8_BIN and all other mysql/mariadb collations (prior to v10.2) remove trailing white space. This is called collations with `PAD`.

As of MariaDB 10.2 new collations with `NO PAD` are added, see [link](https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-102/) This is what we need!
Many of us use a XAMPP stack, which currently included MariaDB 10.1, so I propose to wait until they include the required db version and then update our database schema generator.

Related links:
https://mariadb.com/kb/en/library/char/
https://dev.mysql.com/doc/refman/8.0/en/charset-mysql.html

**Comment by hanjoosten** [comment] 2019-02-05 21:11
Sounds good. This is indeed what we want. So how do we know the time is right to get this done (it is a relatively easy thing to do)

**Comment by Michiel-s** [comment] 2021-09-16 07:52
Duplicate of more recent issue #1212. Same problem identified 5 years later, but we forgot about our analysis here.. Now we'll solve it.

**Closed by Michiel-s** 2021-09-16 07:52 UTC
Labels: priority:low
