### ISSUE TITLE
Fancy model name causes Error when creating database

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#955] opened 2019-05-09 11:46 UTC
Using Ampersand-v3.16.0 [feature/578-navbar:fa9cd8f43], I compiled the script from file
[GRC-Generic-SessionFocus.adl](https://github.com/AmpersandTarski/Ampersand/files/3161923/GRC-Generic-SessionFocus.txt), creating a prototype from it.

I expected that, when initializing the prototype, it would create a database. However, it produced the following error:
![afbeelding](https://user-images.githubusercontent.com/8522589/57451084-811b7d00-7260-11e9-86e9-d6d9809339dc.png)

I have seen this version of Ampersand compile a (very small) script that did not produce this error.

**Comment by RieksJ** [comment] 2019-05-09 11:56
It seems that when I rename the file into `main.adl`, the problem is gone. Apparently, the filename that is specified at compile time is sensitive to SQL-dependencies. Could it be that you cannot have `-`-characters in the filename? @hanjoosten, if you can verify that this issue is caused by constraints that SQL has and that are related with filenames, can you do something about this, preferably modifying stuff to become robust to SQL?

**Comment by hanjoosten** [comment] 2019-05-09 13:07
It turns out that the schema name of the database is the same as the name of the file (without its extension). This has benefits as well as drawbacks:

- Drawback is that the restrictions for a schema name (for MySQL) as for filenames. This might result in an error like this.
- Benefit is that the schema name is very recognisable, which helps when inspection in the database is required for watever reason.

It is thinkable that we introduce a function that takes the filename and spits out a schema name. To make such a function robust, we have to digg into the specification of MySQL for these kind of identifiers. I do not think that is worth the trouble. I could think of a simple function, that removes all characters that are not element of {a..z,A..Z,0..9} from the filename. Then, it takes the first n (let's say 15) of the resulting characters. This will be the schema name. 

Such a function should do the job, while the schema name should stay pretty recognisable in most cases. 
This could be a nice issue to solve for some new contributor. 

Until it is solved, when you run into this, just rename your ampersand file name as a workaround.

**Comment by RieksJ** [comment] 2019-05-15 10:09
I have used `Ampersand-v3.17.0 [development:08ed3010b]` a few moments ago, which is the currently latest commit in the development branch. When attempting to compile the `ButtonCRUD` application (which you can find in ampersand-models repo), I get the same error. I'm not sure though whether or not this has the same cause. It may also be related to #963.

**Comment by hanjoosten** [comment] 2019-05-15 11:25
I do not think these issues are related. The cause of issue #963 causes that no prototype can be generated with the current development version. It has nothing to do with this issue, which is about the name of the schema.

**Comment by Michiel-s** [comment] 2020-08-07 08:28
I think we can close this issue. In Ampersand v3 the default database name was created based on the filename of the entry script:
```
dbName = fmap toLower . fromMaybe ("ampersand_" ++ takeBaseName (fromMaybe "prototype" fName)) $ envDbName envOpts
```

In Ampersand v4 we've changed this. The default database name is now the same as the root context name. This still can lead to naming issues, however, as part of issue #1079 an user friendly error message is given, stating that you should change the context name ór configure a valid database name using environment variable `AMPERSAND_DBNAME` (e.g. in your docker-compose.yaml).

**Closed by Michiel-s** 2020-08-07 08:28 UTC
Labels: bug, component:prototype generator, good first issue, priority:low

**Comment by Michiel-s** [comment] 2020-08-07 08:32
Oh btw, I think there are also less naming issues in the newer versions of MariaDB. 
Looking at [this documentation](https://mariadb.com/kb/en/identifier-names/), I think the database name where this issue started with (`ampersand_GRC-Generic-SessionFocus`) shouldn't be an issue anymore.
