### ISSUE TITLE
smash

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#31] opened 2015-02-23 14:53 UTC
When compiling the file Interfaces.adl, I get the following behaviour:

```
D:\data\sjo00577\Documents\git\ampersand\AmpersandData\FormalAmpersand>Ampersand -fl Interfaces.adl
----------- LaTeX error-----------
File: ts1lmr.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
LaTeX Font Info:    Try loading font information for T1+lmtt on input line 1354
.

("D:\Program Files\MiKTeX 2.9\tex\latex\lm\t1lmtt.fd"
File: t1lmtt.fd 2009/10/30 v1.6 Font defs for Latin Modern
) [19] [20 <D:/data/sjo00577/Documents/git/ampersand/AmpersandData/FormalAmpersand/TechnicalDataModel.png>] [21]
(D:\data\sjo00577\Documents\git\ampersand\AmpersandData\FormalAmpersand\Interfaces.gls [22]
! Use of \\smash doesn't match its definition.
\@tforloop #1#2\@@ #3#4->\def #3 #1}\ifx #3\@nnil \expandafter \@fornoop \el...
l.5 ...etentrycounter[]{page}\glsnumberformat{4}}}

----------------------------------

ERROR: Latex execution failed.
For more information, run pdflatex on: Interfaces.tex
Or consult the log file:
.\Interfaces.log0
```
# Hypothesis

In one of the comments below, @hanjoosten suggests:
"The cause of your problem seems to be a glossary item that does not exist, but it is referenced. (assumably a relation). It would exist iff that relation had either a MEANING or a PURPOSE defined. But since it lacks both, the relation is skipped in the natural language chapter."
Could anyone verify or falsify Han's hypothesis, so as to further this issue?

**Comment by Oblosys** [comment] 2015-02-23 15:59
I can't reproduce this on Mac OS, and on Windows, I get a different latex error:
```
[20]
(c:\Users\martijn\git\ampersand\AmpersandData\FormalAmpersand\tmp\Interfaces.gl
s [21]
! Undefined control sequence.
<argument> \letcs {\glo@name
                             }{glo@\glsdetoklabel {Act}@name}\expandafter \g...
l.5 ...etentrycounter[]{page}\glsnumberformat{4}}}
```
About 4 weeks ago, there have been a number of updates on Latex-related code generation as well as the pandoc template. @hanjoosten: Han, did you test those changes? Errors will probably not show up on the sentinel, as it runs Linux.

**Comment by Oblosys** [comment] 2015-02-23 17:56
After disabling some latex code named 'hack1' everything works as expected (except probably the thing that this hack is supposed to fix).

**Comment by Oblosys** [comment] 2015-03-25 10:46
This hasn't been handled yet. @hanjoosten Can you check what 'hack1' was about, and whether we can remove it completely? (right now it's just commented out)

**Comment by hanjoosten** [comment] 2015-03-25 15:18
The initial problem Stef had with LaTeX, was very likely an installation issue of his MicTex software. (which I know he has tackled lately). 
The Hack1, that Martijn removed, removed a fix with references. This can be seen in chapter 4.1.2, Formal Rules. 

Without hack1 | With hack1
---------------|---------------
Therefore ***2.1*** exists. | Therefore ***Agreement 8*** exists:

The hack is [described here in more detail] (http://tex.stackexchange.com/questions/1230/reference-name-of-description-list-item-in-latex) .

I have undone the removal of Martijn. I tested on Windows, and the hack works fine. So, @Stefjoosten please close this  issue if you can confirm that this also works for you.

**Comment by stefjoosten** [comment] 2015-03-25 15:23
Thanks @hanjoosten for mentioning  (at)Stefjoosten instead of (at)stef. The latter is someone else who is not happy for receiving occasional mails from us...

The solution works for me, so I will close the issue, hoping that Martijn is happy too... (keep my fingers crossed ;-) )

**Comment by Oblosys** [comment] 2015-03-25 22:28
I'm always happy :-) But I still get the same error here, which is not surprising, as the old situation has simply been restored. My MikTex is pretty recent, so I'm not sure what would be wrong with it and whether other people might have this problem as well, but if it works on your installations I'm fine with keeping the ticket closed.

**Comment by hanjoosten** [comment] 2015-03-26 07:01
This is clearly a MikTex issue. However, I remember myself and Stef having difficulties in getting it to work. I remember there was an answer somewhere, telling how to fix the error message. @Oblosys , could you supply the error message you had, so we could add a link to that solution.
The way to go is to generate the .tex file, which is correct. Then see what error message you get and try google.

**Comment by Oblosys** [comment] 2015-03-26 11:42
My error is the one in my comment above. I don't have a solution for it (other than removing hack1 :-) @stefjoosten: do you want me to pursue this? If the problem only occurs in rare cases, we could leave it closed.

**Comment by stefjoosten** [comment] 2015-07-27 08:44
I'm still having this bug, quite consistently by the way. I get  both flavours of messages mentioned above. So Han, could you maybe reinstate Martijn's removal of hack1 or something?

**Comment by hanjoosten** [comment] 2015-07-27 20:00
Removing the hack cannot be the right solution. I'll try to reproduce this tomorrow and see what causes the problem.

**Comment by hanjoosten** [comment] 2015-08-09 10:10
I have not been able to reproduce this. As far as I can tell it must be some specific Texworks installation problem. Sorry.

**Comment by RieksJ** [comment] 2015-11-20 10:42
I recently installed MiKTeX from complete scratch, and I get this error.
I am not at all experienced with this kind of stuff, so I really would appreciate some help here.

**Comment by RieksJ** [comment] 2015-11-20 10:44
When I try to make an fspec, here is what the log says:

	(uetp.gls [127]
	! Undefined control sequence.
	<argument> \letcs {\glo@name 
	                             }{glo@\glsdetoklabel {Account}@name}\expandafte...
	l.5 ...etentrycounter[]{page}\glsnumberformat{4}}}
	                                                  \glsgroupskip
	? 
	! Undefined control sequence.
	<argument> ...glsnamefont \expandafter {\glo@name 
	                                                  }
	l.5 ...etentrycounter[]{page}\glsnumberformat{4}}}
	                                                  \glsgroupskip
	? 
	! Use of \\smash doesn't match its definition.
	\@tforloop #1#2\@@ #3#4->\def #3{
	                                 #1}\ifx #3\@nnil \expandafter \@fornoop \el...
	l.5 ...etentrycounter[]{page}\glsnumberformat{4}}}
	                                                  \glsgroupskip
	? 
	! Emergency stop.
	\@tforloop #1#2\@@ #3#4->\def #3{
	                                 #1}\ifx #3\@nnil \expandafter \@fornoop \el...
	l.5 ...etentrycounter[]{page}\glsnumberformat{4}}}
	                                                  \glsgroupskip
	End of file on the terminal!

**Comment by RieksJ** [comment] 2015-11-20 10:52
When I search Google with the keywords

    "! Undefined control sequence" "<argument>" "\letcs" "{\glo@name"

then this ticket is the topmost in the list! Also, it returns some linkds to documentation, e.g. to [glossaries-code.pdf](https://xml.web.cern.ch/XML/TLLATEST/texmf-dist/doc/latex/glossaries/glossaries-code.pdf). On page 55, this file talks about (how to avoid) 'undefined control sequence's, but I do not have a clue as to whether or not this is relevant/useful.

**Comment by hanjoosten** [comment] 2015-11-20 11:58
Can you reproduce this? (e.g., if you delete all previously generated temporary output files, do you get the same behaviour?) 

Please provide the .ltx file, and/or the model. I don't think this is ampersand related, but I could see if it is reproducable

**Comment by hanjoosten** [comment] 2015-11-20 12:14
The same error message shows up in [this .tex related issue](http://tex.stackexchange.com/questions/1230/reference-name-of-description-list-item-in-latex), that contains a link to another issue with a possible solution.

**Comment by RieksJ** [comment] 2015-11-20 13:44
[UETP.txt](https://github.com/AmpersandTarski/ampersand/files/40078/UETP.txt) Please note that the extension of the file is .TXT so that it could be uploaded. You need to change it into .LTX to run it through pdflatex. (Haven't tried your suggestion of 1 hour back yet)

**Comment by hanjoosten** [comment] 2015-11-20 14:16
The cause of your problem seems to be a glossary item that does not exist, but it is refferenced. (assumably a relation). It would exist iff that relation had either a MEANING or a PURPOSE defined. But since it lacks both, the relation is skipped in the natural language chapter. From somewhere else, it is refferenced, without checking for existence. The diagnosis chapter tells you about this omision. The obvious solution is to document your relations, as suggested in the diagnosis chapter. This is a bug, but I don't think that this will be fixed anytime soon.

**Comment by hanjoosten** [comment] 2016-12-11 14:05
This should be solved in the recent rework on the func. spec. document. Please reopen if you encounter this bug again.

**Closed by hanjoosten** 2016-12-11 14:05 UTC
Labels: bug, priority:low
