### ISSUE TITLE
`API call not found` in tryArch.adl

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#512] opened 2016-08-26 07:23 UTC
I have a nasty bug that I cannot diagnose properly. I have compiled and run a prototype called `tryArch`. Even before it installs the database, it returns "! API call not found". Here is a screen shot together with the information needed to reproduce the error.

![image](https://cloud.githubusercontent.com/assets/275768/17997011/3ab2648a-6b6c-11e6-8447-034e573bf80b.png)

# Reproducing this behaviour
The compiler Ampersand-v3.6.1 [Archimate_extension:5ca6002] has generated the code for [ampersand-models/Blik/tryArch.adl@30a25fa](https://github.com/AmpersandTarski/ampersand-models/blob/30a25fae9320931778211cc8787b83816a0c80e6/Blik/tryArch.adl) using the command:

    D:\git\ampersand-models\Blik> Ampersand --verbose --pD:\htdocs\klad\ tryArch.adl

@RieksJ has tried to reproduce the error using exactly this information, but the error did NOT occur on his machine.

**Comment by Michiel-s** [comment] 2016-08-26 08:23
Easy.. Het pad in je browser is /BLIKgepopuleerd, terwijl je naar htdocs/klad hebt gegenereerd.

**Comment by Michiel-s** [comment] 2016-08-29 11:58
And duplicate of ticket #320

**Closed by Michiel-s** 2016-08-29 11:58 UTC
Labels: bug, component:front-end, priority:critical

**Comment by stefjoosten** [comment] 2016-08-29 12:00
Is indeed a duplicate... thx!

**Comment by teezeequeue** [comment] 2016-09-04 12:58
Hi Stef,

FYI.
These symptoms look very much alike those I experienced a few months ago 
(ticket #409, custom compiled on a linux box).
This could not be reproduced by others.

Best regards,
    Tzadiq
