### ISSUE TITLE
A workflow for running Ampersand locally

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1141] opened 2021-01-30 08:02 UTC
# What happened
I have an Ampersand compiler running on my laptop. I can run the command:
```Ampersand
ampersand proto foo.adl
```
This gives me a directory `.proto` with the following content:
```
Dockerfile              bootstrap               composer.json           data                    gulpfile.js             phpcs.xml               templates
app                     bower.json              composer.lock           extensions              package-lock.json       public                  tests
babel.config.js         changelog.md            config                  generics                package.json            src
```

# What do I do next to get this prototype running?
My assumption is that the ports of `localhost` are available. So I guess I have to make a `docker-compose.yml` file to do the trick...
So should such file not be generated by the `ampersand proto` command?

**Comment by hanjoosten** [comment] 2021-01-30 09:32
This might be a good idea. I cannot oversee this, but it could help to solve the problem that developing with ampersand and testing stuff by generating a prototype has become increasingly difficult. (We spoke about this the other day).

Once we know what should go into these files, it cannot be hard to generate whatever we need. I will then be happy do build that.

**Comment by RieksJ** [comment] 2021-01-30 09:59
You may then also want to include stuff for reading (and delteing/resetting) the log files from the prototype server as a .amplog file so as to facilitate debugging (with the new .amplog syntax coloring).

**Comment by hanjoosten** [comment] 2021-01-30 11:32
Generating stuff isn't the problem. The problem is knowing what to generate. Handcrafted examples will help.

**Comment by Michiel-s** [comment] 2021-02-21 14:17
This is already work in progress. See issue #1093. I'm working on it.

Currently the `ampersand proto` command 1) extracts the prototype framework from Github and 2) generates model files in generics folder. It assumes you have a webserver (Apache) and database (MariaDB) running on your host.
However, we directed our work towards containerization (Docker), so this setup is outdated.

What I think would make sense is to let the `ampersand proto` command add a `Dockerfile` and `docker-compose.yaml` to your working directory. After that you can simply run `docker-compose up -d --build` and you're good to go.

I'll add this comment also in issue #1093. And will start working on that branch again.

I propose to close the issue here.

**Closed by Michiel-s** 2021-02-21 14:17 UTC
