### ISSUE TITLE
Type Checker Issue (or better explanation needed)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#926] opened 2019-04-11 09:44 UTC
I am using AMPvsnr=Ampersand-v3.15.0 [development:a84500c99] to compile the script
~~~
CONTEXT "Issue"
ctrlIsInternal :: Control * Control [PROP]
POPULATION "Mssage" CONTAINS [ "T", "F" ]
RULE "R": ctrlIsInternal;V;"T"[Message] \/ -ctrlIsInternal;V;"F"[Message]
ENDCONTEXT
~~~
This results in a the following error message
~~~
  An ambiguity arises in type checking. Be more specific by binding the Tgt of the expression
     -ctrlIsInternal [Control].
    You could add more types inside the expression, or just write
    (V [Control] - ctrlIsInternal [Control]).
~~~
Since I do not know why the script could be wrong, I assume it is a bug.

**Comment by sjcjoosten** [comment] 2019-04-11 09:49
Here are three ways to fix your issue:

- change the second ``V`` to ``V[Control*Message]``.
- change the string ``-ctrlIsInternal`` to ``(V [Control] - ctrlIsInternal [Control])``.
- add a type in the relevant place through ``I``: by replacing the rhs of the disjunction with ``-ctrlIsInternal;I[Control];V;"F"[Message]``

One of these fixes is given by the error message, and I don't know how that message could be improved, or I don't understand the issue.

**Comment by RieksJ** [comment] 2019-04-11 10:56
For starters, I have no clue how on earth the rule could have type errors. There are no generalizations whatsoever, so I do not see why `-ctrlIsInternal` could be anything else than `V[Control]-ctrlIsInternal[Control`, and consequently, why (either) `V` could be anything else but `V[Control*Message]`. So can you explain which other interpretation for `V` there is that could (somehow) be valid?

**Comment by sjcjoosten** [comment] 2019-04-11 11:20
Sounds like a duplicate of #246 or #437 then? Feel free to reopen if you think this is not a duplicate

**Comment by stefjoosten** [comment] 2019-04-11 15:08
Indeed, we have been here before. I am still searching for an explanation "for students". So let me try and then tell me whether it makes sense.

If the world was closed and this was the only relation in the world, you would be right. However, Ampersand lives in an open world. If tomorrow another relation flies into the context, you are screwed.
@sjcjoosten can you live with this vulgarism?

**Comment by RieksJ** [comment] 2019-04-12 06:49
@sjcjoosten Since it seems that this kind of error occurs once in a while, and is apparently sufficient cause for people (like me) to raise the issue again, could we add a line to the error message saying something like: `For explanations, please refer to https://github.com/AmpersandTarski/Ampersand/issues/246 and https://github.com/AmpersandTarski/Ampersand/issues/437`. This may be slightly out of line with normal error messages, but the benefits of having a practical way to say lots of difficult things outweigh this 'slightly being out of line'. 

@stefjoosten: Having said that, how about making an actual repo that contains explanations that error messages can link to? We would then no longer have to refer to issues...

**Comment by WolframKahl** [comment] 2019-04-12 15:09
> how about making an actual repo that contains explanations that error messages can link to? We would then no longer have to refer to issues...

These explanations should probably just be (sub)+sections of the documentation.

**Comment by hanjoosten** [comment] 2019-04-23 06:17
@RieksJ If you could create a page for elaboration of error messages, that includes a paragraph for this specific error, then I will add a link to it in the actual error message. Then we can close this issue.

- [ ] Add something in the documentation to link to
- [ ] Have the error message link to it.

**Comment by RieksJ** [comment] 2019-04-23 12:49
How about `For explanations, please refer to https://github.com/AmpersandTarski/Ampersand/issues/246 and https://github.com/AmpersandTarski/Ampersand/issues/437.`.

**Comment by stefjoosten** [comment] 2019-04-23 12:56
Adding explanations to the documentation looks attractive, but how are we going to keep the hyperlinks stable? One change in the documentation and all versions of Ampersand produce stale links...

Referring to the GitHub issues is better at preventing stale links (although not perfect). However, it is slightly out of line. If we think a little harder, I'm sure we can find a sustainable way of doing this...

**Comment by RieksJ** [comment] 2019-04-24 06:17
Not having thought on this terribly hard, here is a suggestion: Let every error message be associated with an error-number, e.g. E31. Create a haskell file that allows error-numbers to be associated with explanations and compile it as part of ampersand. Create a switch, e.g. `--explain` or `--error` such that `ampersand --explain E31` shows the associated explanation, or a default text (e.g. `please read the error message carefully, as it is self-explanatory, or if you think that is not the case, please file an issue`). Allow the creation of issues (such as this one) and/or other ways for suggesting explanations for any error that they like. Resolving such an issue means that the suggested explanation, perhaps after having been modified, is associated with the error number in the Haskell file, and hence becomes available in the next release.

**Comment by hanjoosten** [comment] 2019-04-24 06:35
While the sugestion of @RieksJ  is doable, it will cause a lot of work to implement. I do not think it is worth such a major effort. To be honest, I do not think this will get implemented in my lifetime.

**Comment by RieksJ** [comment] 2019-04-24 06:40
@hanjoosten's reaction surprises me. Not being knowledgeable in Haskell, I do know that adding a switch in an application in any other language, whose function is to do an array-like lookup with default behaviour in case the lookup returns something like `void`, would be quite simple. As for the explanations, we can start by leaving everything (except for the error that this issue is about) empty.

I look forward to better ideas (easier to implement).

**Comment by hanjoosten** [comment] 2019-04-24 06:42
I do like the idea of keeping these explanations in the Haskell code. When we get to use RIO (see issue #921), it will become possible to write several types of logging info to the console. I could imagine a switch to have explanations of error messages written in that way.

**Comment by hanjoosten** [comment] 2019-06-12 13:11
In retrospect, we shouldn't make stuff more difficult than it is. If an error is thrown, it should say anything there is to say about it, as long as it is helpfull. On the other hand, we should take care that the error messages stay relevant. 
I object to some kind of conding system for error messages. IMHO that is a wrong solution.

**Comment by Michiel-s** [comment] 2019-07-20 13:38
As @hanjoosten once told me, open issues also have a cost. So if the generic solution we are talking about requires many effort and we think we won’t implement it, I think it is better to just fix the specific error message like @RieksJ suggested and close this issue. I.e. adding a reference to the related github issues in the error message.

**Comment by RieksJ** [comment] 2019-07-21 19:41
Here's a suggestion: the word 'ambiguity' means that there are two or more options to choose from. Currently, the typechecker only informs the developer as to what (s)he can do to fix the error (which is very valuable - we should keep that). But a developer also wants to understand what the ambiguity is. So can @sjcjoosten list the two or more options that the typechecker is unable to choose from. I guess that should close this issue.

**Comment by sjcjoosten** [comment] 2019-07-23 09:23
I'm not able to do that for these disambiguation errors I'm afraid: in many cases the only other option to choose from is a built-in type which the user did not specify. Perhaps the word ambiguity is wrong in this error message.

**Comment by RieksJ** [comment] 2019-07-26 05:42
Let's wait and see if the RIO stuff that @hanjoosten is pursuing will provide a workable solution.

**Comment by hanjoosten** [comment] 2019-07-26 06:00
While it will enable lots of new possibilities, it will do nothing for this one.

**Comment by RieksJ** [comment] 2019-07-26 06:15
@hanjoosten Changing your opinion from [what you said earlier](https://github.com/AmpersandTarski/Ampersand/issues/926#issuecomment-486089698) to your current position is ok. But that is no reason to close the issue. It should be a reason to look further.

The issue is real: 
1. & developers, not necessarily being as well-versed in math as @sjcjoosten and others, are left in the dark which I think is a bad idea.
2. the [explanation](https://github.com/AmpersandTarski/Ampersand/issues/926#issuecomment-482154101) that @stefjoosten gave says that this situation is the result of some further unexplained 'need' to accommodate certain 'future changes' in the code. I would say we cannot predict the future, so rather than accommodating something you don't know is going to happen, simply rerun the typechecker in such cases to see if there are type-errors that need to be fixed.

**Comment by hanjoosten** [comment] 2019-07-26 06:21
> While the sugestion of @RieksJ is doable, it will cause a lot of work to implement. I do not think it is worth such a major effort. To be honest, I do not think this will get implemented in my lifetime.

My earlier thoughts were pretty clear. And as all open issues have a cost, please close this one.

**Comment by sjcjoosten** [comment] 2019-07-26 07:34
I'm guessing it might be worthwhile to add the wontfix label to issues we close(d) because the cost of having them open is too high.

**Closed** 2022-08-15 10:01 UTC
Labels: component:type checker, wontfix
