### ISSUE TITLE
!fatal 286 (module FSpec.SQL)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#152] opened 2015-08-13 09:49 UTC
In a Login INTERFACE, I tried to make a line that says that logging in is futile because there are no Accounts (in which case you obviously cannot login). Here is (an excerpt) of the code that can be compiled by itself:

     CONTEXT Issue152 IN ENGLISH
     
     VIEW SessionProperty: SESSION { value : I } HTML TEMPLATE "PropertyCheckbox.html" ENDVIEW
     
     -- For system bootstrapping purposes, we need a 'God'-account that has all permissions/roles.
     POPULATION Account CONTAINS [ "god" ]
     
     sessionLoginAssist :: SESSION * SESSION [PROP]
     
     INTERFACE "Login" (sessionLoginAssist): '_SESSION'[SESSION]
     ROWS[ "Please help" : sessionLoginAssist <SessionProperty>
         , " " : sessionLoginAssist;V;(-I[Account]!'god');V;'There are no Accounts!!!'[Message]
         ]
     
     ENDCONTEXT

This generates the following message

     ampersand.exe: !fatal 286 (module FSpec.SQL) Ampersand v3.1.0[master:7509cde]
       Can this happen? Here is a case to analyse: (i = 1)
       expr: sessionLoginAssist;V[SESSION*Account];'god'[Account];V[Account*Message];'There are no Accounts!!!'[Message]
       ("fence0",EDcD sessionLoginAssist[SESSION*SESSION])
       ("fence1",EDcV [SESSION*Account])
       ("fence2",EMp1 "god" Account)
       ("fence3",EDcV [Account*Message])
       ("fence4",EMp1 "There are no Accounts!!!" Message)

Apart from the fact that this is a fatal error that should not occur, I have the question whether the expression actually does what it is intended to do, namely show the message 'There are no Accounts!!!' if and only if there are no accounts.

**Comment by sjcjoosten** [comment] 2015-08-13 10:21
I have no idea whether the expression does what it is intended to do either. Why not write this instead:

sessionLoginAssist;V;(I[Account]-'god');V;'There are no Accounts!!!'[Message]

I don't thing the expression will work either, my guess is that the fatal happens as there is no table for "Message".
Rieks: can you verify that this is indeed the problem, by introducing a dummy relation on Message and see if this is indeed a work-around?

**Comment by RieksJ** [comment] 2015-08-13 10:21
Well, I did find an expression that solved my own problem:

                    , " " : sessionLoginAssist;V;(('god' /\ (I[Account]!-'god')));V;'There are no Accounts!!!'[Message]

**Comment by hanjoosten** [comment] 2015-08-13 10:21
Fun! When rewriting the SQL generator a couple of months ago, I remember this situation. I couldn't think of a reasonable piece of SQL to generate for a specific situation. I also couldn't think of a script that could create that situation, so I figured that throwing in a fatal was a reasonable thing to do. Now two things could happen:
  1. the fatal would never occur -> No blood at all
  1. the fatal would occur sometime. -> I made sure that all relevant info would be in the error message.  diagnose will be relative easy because of that.

**Comment by RieksJ** [comment] 2015-08-13 10:25
@sjcjoosten: Your solution does not work, as it shows the message whenever an account exists that is not the 'god' account. The idea is that the message shows when there is only one account, being the 'god' account.

**Comment by RieksJ** [comment] 2015-08-13 11:15
The error seems to be a 'samenloop van omstandigheden'. It will disappear in any of the following cases:

* Remove the `Message` atom
* Replace the `!`-operator with the `;` operator
* Remove the `-`-sign from the expression

And there may be more.

**Comment by sjcjoosten** [comment] 2015-10-26 13:44
I could not reproduce this fatal in the latest version (upgrade_to_haskell_7.10:5828bdd*). Closing this ticket. Feel free to reopen if the error persists on main.

**Comment by sjcjoosten** [comment] 2015-10-26 13:51
Found out how to reproduce (thank you Sentinel): using --validate together with the right script (not the one posted here, but ampersand-models/Tests/ShouldSucceed/Issue152.adl instead) will do the job.

**Comment by hanjoosten** [comment] 2015-10-26 14:29
I know that I can fix this issue whenever I have time for it. I don't think it is hight prio thing though.

**Comment by hanjoosten** [comment] 2016-01-26 06:55
In retrospect, I thought of an example that would still trigger this fatal. I modified Issue152.adl, and that prooved I was right. So this issue has not been solved completely.

**Comment by hanjoosten** [comment] 2016-05-23 14:53
This was a special case, where there was an expression of the form:`...;V[A*B];V[B*C];...`. In this case, at the `;` between the two V's, there must be an atom in B, for the query not to be empty.

**Comment by hanjoosten** [comment] 2016-05-23 15:25
Fixed

**Closed by hanjoosten** 2016-05-23 15:25 UTC
Labels: bug, Case shown in Sentinel, component:prototype generator
