### ISSUE TITLE
Software Architecture for the Ampersand Compiler

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#903] opened 2019-02-02 07:36 UTC
# Problem
Since modern cloud architectures are becoming commonplace, the monolithic architecture of the Ampersand compiler is becoming increasingly irritant. It causes the following problems: (@hidde-jan and @Michiel-s  please add your points to this list)
* Most of us develop on our primary workstation, so we may have additional software or different versions installed. Some of us work on Windows, some of us on Mac. Little differences seem significant. We cannot reproduce each other's problems reliably.
* The developer's workflow differs from one team member to another, which makes it difficult to reproduce each other's problems.
* Images are too large and are sensitive to changes because of dependencies that can be removed.
* Keeping automated build environments in sync for multiple projects and versions with different requirements is error-prone.
* Maintainability suffers from dependencies that have been drawn into the compiler (e.g. latex, graphviz, etc.)

# What do we want?
* An easy standardized developer's workflow, which we can rely on in every environment and publish in "the tools we use".
* To be able to easily update all developers to new and consistent versions, system tools, libraries, and packages.
* Ensure that the test environment is very similar to the production environment.
* Developers shouldn't need to learn all about Docker in order to build their code.

# What do we wish to avoid?
* we want to avoid having to change the developer's workflow. We want it stable.
* we want to shield ourselves from having to know the details of how containerization is implemented.
* The overhead of multiple heavyweight VMs is undesirable.

**Comment by stefjoosten** [comment] 2019-02-02 07:46
# Analysis
Coordination between components of the Ampersand compiler is now largely done in module `components.hs`. The architecture is roughly described by the following picture (from 2015)
![968634051](https://user-images.githubusercontent.com/275768/52161555-e04c7d00-26c6-11e9-9fd5-da9f5ec50518.png)

**Comment by hanjoosten** [comment] 2019-02-02 08:01
The Tex stack has become optional. Only LaTeX and PDF output depends on it. Focus has been moved to the .docx format (=Word). So in many cases the Tex stack could be left out. 

Graphviz is very stable. As far as I know, it is still on version 2.38, which is from 2014.

**Comment by stefjoosten** [comment] 2019-02-02 15:30
# Choices (please agree or disagree)
* Streams are great to make components independent. Components that can be transformed to stream processors (streams in - streams out) can be put in a container.
* The main streams in a container shall be configured stdin, stdout, and stderr, to adhere as much as possible to mainstream (:-)) unix conventions.
* Streams are homogeneous, i.e. all elements in a stream have the same type.
* In the architecture map we will mention the type (e.g. `A-structure`), the protocol (e.g. AVRO) and the channel names (ports) explicitly for every stream. (By the way: Haskell has an AVRO package, which makes AVRO a good candidate for (de-)serializing complex Haskell data structures.)
* We will not "overdo" things. A simple cascade of modules can just as well be integrated into one container.

Here is a first proposal (containers are drawn as circles, application components are drawn within a container). I have not fitted all components in this drawing yet, but the mainstream is here.
![ampersand compiler architecture](https://user-images.githubusercontent.com/275768/52165912-20335480-2707-11e9-97b5-9f0bc6ae77fd.png)

**Comment by hanjoosten** [comment] 2019-02-02 15:52
I am confused. On every edge in your drawing, there is a representation of the data that should be delivered in an event. The recieving component must be able to parse that again. This seems a lot of work, and I see no proper motivation to do so, other than to make the components more tangeble. @stefjoosten please provide proper motivation about why we need this at the level you are proposing.

**Comment by hidde-jan** [comment] 2019-02-04 16:06
I think you're going a bit too far in 'containerizing'. I would break ampersand itself up into different containers, but I would make it so that ampersand never calls any other executable or script outside of itself. So ampersand should never call composer or (xe)(la)tex itself.

Ampersand should only take ADL files (and possibly excel-files) and as its output have files that are usable by other programs.

Stef and I had a discussion about this last week, but I might have given the wrong impression that we should pass everything over STDIN to be more unix-like. What I meant was that each part of the ampersand compiler should not do more than absolutely needed and that the ampersand compiler in total should not call other executables (by default) or require other executables to be installed.

From a user-experience point of view, I understand that you want ampersand to be a batteries-included kind of binary. That's fine, but what I would do in that case is take the git-like approach and use sub-commandos. For instance `git clone` is actually `git-clone` hiding behind the `git` binary. There's nothing wrong with having a `ampersand prototype install` subcommando that installs npm and/or composer packages or a `ampersand prototype up` commando that starts docker containers, but you don't want the Prototype 'outputter' to do that directly.

**Comment by stefjoosten** [comment] 2019-04-02 19:58
OK. I am convinced that my proposal is not good. We need a different architecture. I'll remove the ideas above (and the comments) in a short while, because we're backtracking to the original problem.

I am inspired by the "daemon" feature that @hanjoosten  has built. He has made a daemon that merely checks a script for errors (i.e. the behaviour of Ampersand without options). The value is that this deamon makes real time checking possible because it reacts (practically) immediately to every change in the script.

Carrying on along those lines, I can see a cluster of containers that builds a docker image in real time, reacting on every edit that is being saved. It consistst of 4 concurrent processes (each in a container of its own):
1. the editor, which is a container with only VS-code in it. It changes the Ampersand script by a user who edits it. The script itself can be outside the cluster through a volume link, so it survives taking down the cluster.
2. the Ampersand compiler, which generates the intermediate JSON-files in real time by reacting on changes in the Ampersand-script.
3. the prototype generator, which generates a web application in real time by reacting on the changes in the JSON-files.
4. the bakery, which bakes the application and wraps it in a docker image, ready to be used anywhere. The resulting image is written in a docker repo outside the cluster through a volume link, so it will survive the cluster. 

Here is the architecture:
![Untitled Diagram-Page-2](https://user-images.githubusercontent.com/275768/55430565-bdd3c480-558e-11e9-98e9-66eceff6fd1d.png)

Some benefits of this architecture are:
* Every container is small because it contains necessary stuff only.
* Each container image can be developed by different people, independent of each other.
* This architecture is cloud-ready, scalable, etc. so it can be run on any (dockerized) laptop, in the cloud, in university data centers and even in TNO's data center without changing anything but a (software encoded) configuration file.

We need to pay attention to the definition and standardization of the .json interface, to create as much independence between the Ampersand compiler and the prototype generator as possible.

@hidde-jan, @Michiel-s, @hanjoosten  please share your ideas and criticisms below, to see if we're making progress.

**Comment by hidde-jan** [comment] 2019-04-03 07:46
Hi Stef,

Just my comment here. I don't want to sound negative, but I think what's described here is also not the right way to go.

>  I'll remove the ideas above (and the comments) in a short while.

Discussions are pretty important and should be preserved. If you want a clean slate, just close this issue and create a new one with the same content, including a link to this previous issue.

> Carrying on along those lines, I can see a cluster of containers that builds a docker image in real time, reacting on every edit that is being saved. It consists of 4 concurrent processes (each in a container of its own)

This is actually completely different than the approach described in your link. In their process, the ampersand executable would spin up an ephemeral container, use it to build the source, then discard the container again.

> the editor, which is a container with only VS-code in it (or any other ASCII editor). It changes the Ampersand script by a user who edits it. The script itself can be outside the cluster through a volume link, so it survives taking down the cluster.

The design for the rest of ampersand should be completely separate from how one chooses to edit the ADL files. You can build an easy web-based GUI/IDE on top of ampersand, but that shouldn't have anything to do with how you actually build a prototype.

> The value is that this deamon makes real time checking possible because it reacts (practically) immediately to every change in the script.

I have only briefly looked at this daemon, but it seems you need to start by specifying which files you want it to watch. If you look at other languages, linters are often just called with a specific bunch of files and output problems. Real time checking is done through other programs, watchers that invoke the linters when a file changes, or editors that invoke the linter on save.

I think the big problem here is that we are talking about different things:

1. The architecture of ampersand as a Haskell program
2. The architecture of ampersand as a compiler of ADL scripts to prototypes/tex/etc
3. The architecture of a environment that lets people easily write ampersand scripts and test/run prototypes
4. The architecture of having the ampersand toolchain interact with (for instance) VSCode

These are very different problems which are, for the most part, orthogonal. I think currently 2 and 3 are pretty much interwoven in this issue. We should separate these out. I also do not really see the need to daemonize everything. Stack's approach seems much saner:

> When Docker is enabled in stack.yaml, every invocation of stack (with the exception of certain sub-commands) transparently re-invokes itself in an ephemeral Docker container

Whatever architecture is chosen, I think the following things are important to realize:

1. You should be able to run (all) ampersand commands without docker. This doesn't mean you can't build something like slack above, but even if you use docker, you need to make ampersand do something inside a docker container, or it is containers all the way down.
2. Ampersand should be able to generate to generate any build artefact without needing the consumer of that artefact to be installed. I.e. you shouldn't need latex installed to have ampersand generate a .tex file, you shouldn't need to have php installed to generate a prototype. This is very important in keeping ampersand, and ampersand containers, focussed and lean. This doesn't mean we can't create images that are able to run prototypes.

I'm also not convinced on the necessity of having intermediary JSON artefacts. There is already the FSpec to act as the intermediary artefact which can be consumed by any compiler.

**Comment by stefjoosten** [comment] 2019-04-03 09:13
Great comment, @hidde-jan! You make me curious about your ideas on the way to go for solving the problems mentioned in the opening comment... Do you have anything in mind?

I think the drawing I made is an initial architecture for a portable IDE-pod for Ampersand, to be used in RAP, on personal laptops, on public sites, etc. So yes, I am drifting away from the title of this issue... However, I think this thinking is relevant for the compiler architecture itself, because the way it is used should steer how we build it.

You are quite right that the four containers in this pod solve orthogonal problems. The editor, the Ampersand-compiler, the prototype generator are quite independent. Isn't that precisely what we want in a pod that brings together such components in an end-user application? In my drawing I have left out the functionality for functional specifications and other goodies, merely concentrating on the prototype generation.

**Comment by hanjoosten** [comment] 2019-04-03 09:17
Nicely put, @hidde-jan ! These are all good points. Especially I like the two requirements you finished with. Fortunately, both of these invariants still hold today (only graphviz is an exception). The JSON artefacts are part of the generated prototype. There is no need to have php, mysql, TeX, docker or whatever to be installed to use the ampersand generator. 
The only exception, Graphviz, has to be installed when commands are used that create graphical output (e.g. `--fspec=FORMAT` ). If we want, we could introduce a switch to produce .dot files instead of the current graphical output formats quite easily. 
The requirement for TeX to be installed is only when the `FORMAT` is Pdf. Currently, if format = LaTeX, no TeX is required.

**Comment by hidde-jan** [comment] 2019-04-03 12:15
> The JSON artefacts are part of the generated prototype

From what I understand, Stef's proposal is to have JSON act as an intermediary artefact that is fed to the compilers/generators that turn that output into the actual artefacts (.tex, prototypes, etc). Currently, the `FSpec` is the output of component of ampersand that takes ADL scripts and computes and checks all concepts and relationships. So this would mean creating `FSpec -> JSON` and `JSON -> FSpec` translation layers which means extra code, extra moving parts, and extra bugs. If this doesn't seem correct, please let me know.

As to Stef's question about the issues above:

- > Most of us develop on our primary workstation, so we may have additional software or different versions installed. Some of us work on Windows, some of us on Mac. Little differences seem significant. We cannot reproduce each other's problems reliably.

    Here the problem is twofold: that ampersand itself isn't compiled in a reproducible way, and that things build/compiled with ampersand aren't build in a reproducible way. The first problem could be fixed by using the [two dockerization feature of stack](https://docs.haskellstack.org/en/stable/GUIDE/#docker), the second problem could be fixed by copying what stack did, i.e. add an option to ampersand to compile a script inside a docker container. The problem is already partially fixed because the official ampersand executables are build on travis, so anyone using an official ampersand binary actually has the same binary. The second problem is partially fixed because we can create or pull docker images containing the latest ampersand binaries.

- > The developer's workflow differs from one team member to another, which makes it difficult to reproduce each other's problems.

    Workflows differ. Not everybody uses the same text-editor and system. This shouldn't be a problem if your test/build environment is consistent.

- > Images are too large and are sensitive to changes because of dependencies that can be removed.
Keeping automated build environments in sync for multiple projects and versions with different requirements is error-prone.

    I don't really understand what is said here and what the issue is. Especially the last sentence. What do you need to keep 'in sync'?

- > Maintainability suffers from dependencies that have been drawn into the compiler (e.g. latex, graphviz, etc.)

    From Han's comment it seems that this is no longer the case. Doesn't ampersand call composer when generating a prototype? This is also easily fixable it seems.

**Comment by hanjoosten** [comment] 2019-04-03 12:53
Yes, I forgot about composer. About a week ago I heard @Michiel-s say that that should be made optional by using a switch as well. This might be implemented as we speak in the navbar feature branch. If not, it should be very easy to do.

I agree with @hidde-jan that development workflows will be different. There is no need to force that for every developer. The problems some of us have with their current haskell workflow is not going to be solved just like magic by adding docker to it. 

Our users, the ampersand modellers, could benefit from easy installation, but these are separate issues. What exactly are we trying to solve here?

**Closed** 2021-06-02 04:18 UTC
Labels: Discussion, deployment
