### ISSUE TITLE
FATAL generated by CLASSIFY

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1014] opened 2019-09-20 06:01 UTC
I use Ampersand-v3.17.2 [development:254cacd10] to compile the following script:
~~~
CONTEXT Bug

CLASSIFY CVE ISA CVE

ENDCONTEXT
~~~
I expect this script to either compile or provide a cool error message.
Instead, the following fatal error was generated:

![afbeelding](https://user-images.githubusercontent.com/8522589/65302898-d22b6e00-db7c-11e9-9a7a-1d98f3ceda46.png)

**Comment by hanjoosten** [comment] 2019-09-20 06:13
Hmm. This issue keeps comming up. See #742 and #896. The latter has been closed premature. The issue is not that we do not allow these alias-like statements, the issue is that this leads to a fatal error message. 
So let's close this issue only if the above script does not generate a fatal, but either is accepted or leads to a user-error message.

**Comment by sjcjoosten** [comment] 2019-09-20 14:24
So maybe @RieksJ can answer the question implicit in this issue: do you want a warning, an error, or no output for this script? (I don't quite understand why you would write such a thing as ``C ISA C``, so I would say warning, but you often have good reasons for writing things that no one else has thought of)

**Comment by RieksJ** [comment] 2019-09-23 04:39
Let us treat it in the same way as we would treat `RULE "risr": r=r`. So it does not generate an error or warning. It is of no consequence in a prototype. It would generate text for a functional spec.

**Comment by stefjoosten** [comment] 2019-09-24 18:55
In this particular case, the semantics of Ampersand says that the set of concepts in this context is `{CVE}`. This would have been the empty set if Rieks had left out the `CLASSIFY` statement. So this script has meaning. Needless to say that `CVE ISA CVE` is redundant because ISA is reflexive anyway. So I would consider a warning quite appropriate.

**Comment by RieksJ** [comment] 2019-09-27 08:22
I do not consider 'redundancy' a sufficient reason for producing a warning (nor for the appropriateness of a warning). If it were, then `r::A*B  ... lots of other script texts ...   r::A*B` should also produce a warning. I would object to that because having such redundancy actually serves a purpose, which is that it allows me to split code over multiple files yet keep code that belongs together in a single file, and also it allows me to comment out the inclusion of a file that defines relations yet define one or two of the relations in another file as they are needed to stub the commented out functionality. 

I suggest to _only_ produce a warning if there is real purpose to do so. For now, I do not see it.

**Closed** 2020-01-31 07:53 UTC
Labels: bug, component: compiler
