### ISSUE TITLE
Check required for atoms w.r.t. technical type

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1188] opened 2021-07-09 08:24 UTC
This issue is the follow-up of issue #1184. It aims at preventing that sort of problem from occurring in the future.

# What happened
I've spent over a day's effort over a period of several weeks to get a diagnosis on issue #1184, and that is frustrating for a stupid error like this. This error could have been caught in the compiler (something like checking on the length of strings in view of the technical type), but it wasn't. It could have been caught in the back-end (something like checking the JSON-file that atoms match the technical type), but it wasn't. This thing "fell through" to the level of the database and gave error messages that are unrelated to the problem and therefore difficult to diagnose. 

@hanjoosten and @Michiel-s , do you have a good idea for a solution?

# The problem
The compiler does not check that a string matches the default technical type, `ALPHANUMERIC`. As a consequence, excessively long strings may cause unpredictable errors coming out of the database. The problem is that such errors are extremely laborious to fix.

**Comment by Michiel-s** [comment] 2021-07-13 18:03
@stefjoosten How many characters was the string you were dealing with? And what was the situation? Did you specified it as default population in ampersand script? Or tried to insert it in a prototype interface? And how did the database respond? Cut of at certain length or error? Was that error shown/returned to user?

The database field type and length for ALPHANUMERICs are VARCHAR(255)

**Comment by Michiel-s** [comment] 2021-07-13 18:03
And frustrating that it cost you that much time to diagnose I think.

**Comment by Michiel-s** [comment] 2021-11-13 15:52
Duplicate of #1199

**Closed by Michiel-s** 2021-11-13 15:52 UTC
Labels: bug, component: compiler
