### ISSUE TITLE
Preventing run-time messages

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#813] opened 2018-07-23 08:45 UTC
The refactored interface forbids some situations and gives an appropriate (red) error message. Some of these situations can be detected at compile time, and therefore they should. In this issue I will list the ones that I run into. Feel free to add your own instances.

 - [ ] There is no interface of type `SESSION`
(detected in Ampersand-v3.11.0 [HEAD:d1ce3dd*], build time: 06-Jul-18 06:42:49 UTC)
![image](https://user-images.githubusercontent.com/275768/43066534-38f8b95a-8e65-11e8-82f1-d13e1f1f9973.png)
I don't think we want to force the Ampersand user to always have this interface. Instead, I think we should generate a default interface if the user doesn't.

**Comment by hanjoosten** [comment] 2018-07-23 08:53
Instead of having one issue with all these cases, I would prefer each of these to have an own issue. The work that has to be done is likely to be very different for each of them.

**Comment by hanjoosten** [comment] 2018-07-23 08:54
Also, a minimalist .adl file would help to reproduce each issue

**Comment by RieksJ** [comment] 2018-09-07 06:09
I wholeheartedly agree with @stefjoosten that illegal situations that can be detected at compile time should be detected at compile time. However, the non-existence of an interface of type SESSION is not necessariliy illegal. It may be argued that for RAP this would be the case, but for general users of Ampersand, I do not see why it should - a warning should suffice.

Perhaps we should think about different compilation ways so as to facilitate BeginningUsers, GeneralUsers and ExpertUsers, where beginners will face lots of errors because they try to do stuff that is not for beginners, general users face only a subset of such constraints, and experts only have what is really always wrong. And I do not mind the 'BeginnerUser' being the default setting.

**Comment by Michiel-s** [comment] 2018-11-28 21:15
The error as shown in the figure above has nothing to do with an interface, but is caused due to an error during database creation. Somewhere in creating tables an error occurred (e.g. due to #838) which is why the table for concept SESSION is not created. This table is updated during application initialization, because the current session is inserted or lastaccess is updated. The error you see above specifies that this table does not exist.

No worries, this issue will be fixed together with #819 and #829. In fact it is already fixed, but is available when new release of Prototype framework is included in Ampersand generator.

**Closed by Michiel-s** 2018-11-28 21:15 UTC
Labels: Beginner-friendly, component:global, priority:normal
