### ISSUE TITLE
Rule: `Every relation in SystemContext.adl must have a transformer in Transformers.hs`

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#957] opened 2019-05-11 12:39 UTC
Ik heb zitten knutselen aan de SystemContext in de branch `feature/5780navbar`. De bedoeling is om deze wat meer body te geven zodat het rollen-spel beter gaat. Feitelijk heb ik een aantal zaken uit SIAM die daarmee te maken hebben in de SystemContext gefrot. Het vertaalt prima, maar als ik er een prototype mee wil maken krijg ik de volgende melding voor mijn kiezen:

![afbeelding](https://user-images.githubusercontent.com/8522589/57569778-4e0cf100-73fa-11e9-93a3-c0f77bd40640.png)

Ik weet niet goed hoe ik hier verder mee moet. Iemand een idee?

**Comment by hanjoosten** [comment] 2019-05-11 12:51
This error message is by design. It enforces synchonicity between 
 - the relations defined in the .adl files of systemContext and 
 - the Haskell code that populates these relations with the information from a user's script.

**Comment by hanjoosten** [comment] 2019-05-11 13:00
In this case, you have been tinkering with the .adl files. There are a couple of things you should be aware of (in no particular order)
  - You need to recompile ampersand.exe, to get these changed .adl files into ampersand.exe
  - If you get above error message, it tells you what relations exist in one of the above sides, but not in the other. It suggests that Transformer.hs does not know about how these relations should be populated, based on a user's script.

I might be able to help you with this, but then I need to know how you expect these new relations to be populated.

**Comment by RieksJ** [comment] 2019-05-11 15:00
I do not currently expect ampersand itself to populate any of these relations, except for the following: `systemRole[Role*Role]`, which should be populated with
~~~
POPULATION Role CONTAINS ["User", "Anonymous", "SYSTEM", "ExecEngine" ]

POPULATION systemRole CONTAINS [ ("SYSTEM", "SYSTEM") ]
POPULATION systemRole CONTAINS [ ("Anonymous", "Anonymous") ]
POPULATION systemRole CONTAINS [ ("ExecEngine", "ExecEngine") ]
~~~
Does that help?

**Comment by hanjoosten** [comment] 2019-05-11 15:06
Yes. I guess so. I'll have a look.

**Comment by Michiel-s** [comment] 2019-05-11 20:43
I don’t like where this is going. We should be aware of and guard the purpose of the SystemContext. It is there for basic stuff that is needed to be able to run a prototype. Out of the box, by default.

The things Rieks is adding are parts of SIAM. Ampersand modelers that need those things can add them by simply including (parts of) SIAM. SystemContext is for those things you always need even if you don’t have a login, agent , agent account or whatever. Same for all the properties on SESSION concept. It adds complexity that is not needed.

**Comment by hanjoosten** [comment] 2019-05-12 05:02
I agree with @Michiel-s. He has a good point about making stuff too complex. There is no need to add any of the SIAM stuff into SystemContext. I think the modifications made should be reverted, before this is merged into development.

**Comment by RieksJ** [comment] 2019-05-12 12:19
I was just trying to be helpful. Since we are already adding complexity anyway - e.g. adding NavBar editing facilities - I thought it was a good idea to include the rules that determine which roles can(not) be allowed/activated/shown in the different kinds of sessions, which would make life easier when implementing front-end stuff, such as what roles to show in the role-selection menu, and what roles to use for making interfaces available in the different kinds of sessions. 

But then, I don't mind if these rules are only implemented in the front-end javascript, provided that they are implemented as specified, which currently is not the case.

**Comment by stefjoosten** [comment] 2019-05-14 20:45
What is the purpose of SystemContext precisely? Do we have a statement-of-purpose, which makes it obvious why something should be in or out?

**Comment by RieksJ** [comment] 2019-05-15 07:25
The purpose of SystemContext (and I guess it should be in the `SystemContext.adl` file) is to have the prototype generator populate a number of concepts/relations that developers do not expect to have to populate themselves. One example is that ExecEngine is a (system) Role.

Another purpose is to specify the set of rules that provide guarantees that the backend/frontend relies on. One example is that system roles must not be activated in sessions.

Activities in the feature/NavBar-branch have seen function-creep: it now also specifies meta-relations for interfaces that help the backend do nice things with the navbar. Further function-creep (by me) has added some SIAM-related stuff. @Michiel-s and I (and @hanjoosten) agree that this is not the way to go. @Michiel-s and I are working to clean this stuff up.

**Comment by Michiel-s** [comment] 2019-05-17 12:05
I still see activity in the 578-navbar branche (@RieksJ merged development into this branche). However, we agreed to take a step back and decide what should be included and what not. So the source will be the development branche. Not need to update the current 578-navbar branche.

- [ ] we can delete the 578-branche. @RieksJ could you do so
- [ ] close this issue
- [ ] continue our discussion in #578

**Comment by RieksJ** [comment] 2019-05-18 04:42
Let's not prematurely discard all the work just yet. So no, I won't delete the 578 branche (yet). I will close the issue, I will go back to using the development branch again, and continue discussing in #578.

**Comment by hanjoosten** [comment] 2019-05-18 08:56
In that case, please replace the branch with a tag, conform the purpose of branches and tags.

**Comment by RieksJ** [comment] 2019-05-18 09:18
???

**Comment by hanjoosten** [comment] 2019-06-12 12:42
I have deleted the branch, and replaced it with this tag [taggedBecauseIssue957](https://github.com/AmpersandTarski/Ampersand/commits/taggedBecauseIssue957)

**Closed by hanjoosten** 2019-06-12 12:42 UTC
Labels: Discussion, component:meatgrinder, component:prototype generator, question
