### ISSUE TITLE
Inserting link fails, but should succeed

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#563] opened 2016-11-07 14:20 UTC
In RAP3, I get the following error message at runtime:

![image](https://cloud.githubusercontent.com/assets/1159672/20060385/38b83f6a-a4fb-11e6-9558-b2a52d58e479.png)

The link that the execengine is trying to set is diagRequest[ScriptVersion*ScriptVersion]. The atoms are ScriptVersions, but they are also Item. (ScriptVersion ISA Item ) I would say that it it totally valid to insert this pair as a link in the relation. 

(This is the behaviour in RAP3, the branch called `performanceTestingRAP`. )

**Comment by hanjoosten** [comment] 2016-11-07 16:10
@Michiel-s and I have discussed this bug online. Fortunately, there is a workaround. @Michiel-s now also knows how to fix the bug.

**Comment by Michiel-s** [comment] 2017-12-14 18:57
If you're okey with it I'll close this issue. I believe this is fixed in commit c782f79baa21f1fa9ec156c85966fbb66610b132, but I cannot reproduce the situation to be sure.

**Closed by Michiel-s** 2017-12-14 18:57 UTC
Labels: bug, component:html/js front-end
