### ISSUE TITLE
Bug in Ampersand -fl when generating DTV.adl

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#58] opened 2015-04-07 20:11 UTC
The file DTV.adl [8db95f2] is compiled properly into a working prototype by means of Prototype v3.0.3[no git info], build time: 07-Dec-14 09:31:20. It can even generate a DTV.tex file...

However, when compiling with Ampersand v3.0.3[master:8df0d1f], build time: 07-Apr-15 21:59:08, we get a fatal 260 from P2A_Converters: 

    D:\git\ampersand-models\NVWA DTV>Ampersand DTV.adl -fl --verbose
    Reading file DTV.adl
    Reading file D:\git\ampersand-models\NVWA DTV\Login.adl
    Reading file D:\git\ampersand-models\NVWA DTV\Tijdvakken.adl
    Reading file D:\git\ampersand-models\NVWA DTV\Diensten.adl
    Reading file D:\git\ampersand-models\NVWA DTV\Referentielijsten.adl
    Reading file D:\git\ampersand-models\NVWA DTV\Medewerkers.adl
    Reading file D:\git\ampersand-models\NVWA DTV\Tijdverantwoordingen.adl
    Reading file D:\git\ampersand-models\NVWA DTV\Periodeverantwoordingen.adl
    Reading file D:\git\ampersand-models\NVWA DTV\MedewerkerRechten.adl
    Reading file D:\git\ampersand-models\NVWA DTV\Resultaten.adl
    Reading file D:\git\ampersand-models\NVWA DTV\Urenpools.adl
    Reading file D:\git\ampersand-models\NVWA DTV\PDirektBestanden.adl
    Reading file D:\git\ampersand-models\NVWA DTV\PopForDTVtesting.pop
    Reading file D:\git\ampersand-models\NVWA DTV\History.adl
    Processing DTV
    Using Template: D:\git\ampersand\.cabal-sandbox\x86_64-windows-ghc-7.8.4\ampersand-3.0.3\AmpersandData\..\outputTemplates\default.latex
    Generating latex to : .\DTV.tex
    Ampersand: !fatal 260 (module ADL1.P2A_Converters) Ampersand v3.0.3[master:8df0d1f]
      the technical type should be derived from the conceptdefs of this concept.

**Comment by hanjoosten** [comment] 2015-04-08 08:08
This is a known bug. Actually, 7 of the current tests in sentinel fail because of this one. The smallest script is probably Tests/ShouldSucceed/SequencesBug.adl

The problem is, that during typechecking, A_Concepts can be created, without a proper value for the field cpttp. This field contains the technical type of the concept, which isn't known at that point. 
The solution would be to get rid of that field, and get another way to find out what the technical type of a concept is. The technical type of a concept is given in its concept definition(s). However, since the relation 
```
definedBy [Concept*ConceptDef] 
```
isn't TOT nor UNI, for good reasons, it isn't trivial how to obtain the technical type of a concept. This obviously needs rethinking.

**Comment by hanjoosten** [comment] 2015-04-08 10:43
It turned out that the field wasn't used any more. @RieksJ

**Comment by hanjoosten** [comment] 2015-04-08 10:44
I also close this issue for now. The code contains a TODO, so this will not be forgotten.

**Closed by hanjoosten** 2015-04-08 10:44 UTC
