### ISSUE TITLE
Funny behaviour of integers in spreadsheet include.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#262] opened 2016-01-06 10:03 UTC
The inclusion of spreadsheet `ProductCodes.xlsx` shows erratic behaviour:
~~~~~~~~~~~~~
Reading file Arch.adl
Reading file ProductCodes.xlsx
Reading file Wetsartikelen.xlsx
Error(s) found:
Representation mismatch
    Found: `42005.0`,
    as representation of an atom in concept `Datum`.
    However, the representation-type of that concept is (implicitly) 
    defined as ALPHANUMERIC. The found value does not match that type.
  "ProductCodes.xlsx":
   Sheet: Strategische planning, G3
~~~~~~~~~~~~~~~

This issue is visible by executing the prototype ampersand-models/Blik/Arch.adl in of commit AmpersandTarski/ampersand-models@142cac661df8e3855f3c6f5552c36b1fc69fb202, which has been compiled with Ampersand v3.3.0[master:c3382b6*], build time: 29-Dec-15.

This issue did *not* occur when executing the same file, but compiled with Ampersand v3.1.0[master:ac300ab], build time: 05-Oct-15.

**Comment by hanjoosten** [comment] 2016-01-06 11:29
This is a duplicate of issue #260

**Closed by hanjoosten** 2016-01-06 11:29 UTC
Labels: bug, component:parser
