### ISSUE TITLE
Populating isa[Device*ArchiObject] results in unexpected rule violations

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#647] opened 2017-03-26 10:57 UTC
Processing of the Archisurance repository results in numerous unexpected violations, preventing prototype generation. The violations occur with the population of the relation isa[Device*ArchiObject] [UNI, INJ].
These errors did not occur on previous compilation with Ampersand version 3.7.1. The input files are unchanged (except for the markup section markers {+ +}).

![image](https://cloud.githubusercontent.com/assets/22689893/24330645/7f33657e-1223-11e7-904a-e774872403cf.png)

[Archisurance.zip](https://github.com/AmpersandTarski/Ampersand/files/870691/Archisurance.zip)

**Comment by hanjoosten** [comment] 2017-03-26 12:26
I have tried to verify your claim. I built the version 3.7.1 with the archimate extention of Ampersand. I changed the {+ +} syntax to the old {+ -} syntax. Then I tried to create a prototype. However, the Archisuranc.xml could not be read, because it has some new format. 

When I use the newly created 3.8.3 version I was able to reproduce your error. I am not familiar with what you are trying to do, but the first violation is a violation of the injectivity rule of the relation isa[Device*ArchiObject]. I searched for 'Products' in the .xml file, and found it as the name of two distinct folders. Are you sure the relation should be injective?

**Comment by filetp** [comment] 2017-03-26 14:05
Hi Han,
I've just created another prototype using Ampersand v3.7.1. To be sure I added the Archisurance.adl and the Archisurance.xml files again. The Archisurance.xml file is (imho) unchanged. The Archisurance.adl is slightly newer (since it is under continuous construction). Could you try again plz?
[Archisurance v371 take 2.zip](https://github.com/AmpersandTarski/Ampersand/files/870796/Archisurance.v371.take.2.zip)

**Comment by hanjoosten** [comment] 2017-03-26 14:22
Well, I still get the same lex error on reading the .xml file. The archimate tool has moved up to a newer version, as @stefjoosten had noticed before.

Having said that, even if it would have run in the old version without violations, in the current version violations are detected. That check is pretty solid, so I would be pretty convinced there is something wrong with the (meta)model.

**Comment by hanjoosten** [comment] 2017-03-26 14:58
This is something for @stefjoosten to look at. I have done an experiment, by removing the INJ and UNI rules on the isa relation (ArchiAnalize.hs, line 478). This results in a database being generated, but this is definetly not in the way that we would want. 
I guess that Stef should thing about what the smerigeIdentifier should be for ArchiObjects. Now I see all different things being used for those.

**Comment by stefjoosten** [comment] 2017-03-27 09:32
This should be fixed now (commit @46a0cc44881497709797b494787987727868efc2). @filetp Peter, would you please verify?

**Closed** 2017-03-27 09:32 UTC
Labels: Archimate extention
