### ISSUE TITLE
Request to allow VIEWs to work on TXT "..." constructs

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#942] opened 2019-05-01 16:46 UTC
It isn't that long ago that `INTERFACE`s have been provided with the capability that `VIEW`s already had, namely to provide use the construct ` "label": TXT "text" `, which allows developers an easy way to embed fixed texts. 

Previously, you had to define some concept, e.g. `IfcText` as an `ALPHANUMERIC`, and whenever you would use  a construct such as ` "label": V;"here goes my text"[IfcText] `, you also needed to provide the statement ` POPULATION IfcText CONTAINS [ "here goes my text" ]`, which was a hassle.

The current ability to use the construct ` "label": TXT "here goes my text" ` in `INTERFACE`s is consistent with how it is used in `VIEW`s. However, there is a drawback: I can specify a `VIEW` for `IfcText`s, e.g. to make them bold, or use a larger font. I cannot use `VIEW`s behind a `TXT` statement in interfaces.

This issue requests for a feature being implemented, being that within an `INTERFACE`, a `TXT "string"` sequence can be followed by a `<VIEW>`, which MUST be defined (e.g.) using `TXT` as its concept. Thus, I could create bold (strong) texts by creating a template STRONG.html and defining the view
`VIEW STRONG: TXT { "label": I } HTML TEMPLATE STRONG.html ENDVIEW`

**Comment by Michiel-s** [comment] 2021-11-13 14:19
Largely duplicate of #1112. Feature request will be possible when that other issue is implemented.

**Closed by Michiel-s** 2021-11-13 14:19 UTC
Labels: priority:low, enhancement, component:prototype generator, component:parser
