### ISSUE TITLE
New Excel Import does not create specialized atoms

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#408] opened 2016-05-02 12:33 UTC
Consider the following:
~~~
CLASSIFY Concern ISA Variable
varAgreement :: Variable * Agreement [UNI,TOT]

INTERFACE "#Concerns" FOR ExcelImporter: I[Concern]  CRud BOX
   [ "Agreement" : varAgreement CRUd 
   ]

INTERFACE "Concerns" FOR User: V[SESSION*Concern] cRud COLS
   [ "Concern" : I cRud
   , "Agreement" : varAgreement cRud
   ]
~~~
Consider the following Excel sheet
![picture1](https://cloud.githubusercontent.com/assets/8522589/14954384/3a16eb0e-1072-11e6-973b-554df9249ff9.png)
After importing this population, they should show up in the interface `Concerns`, but they do not. It appears as if they are created as a `Variable` rather than a `Concern`

**Comment by Michiel-s** [comment] 2016-07-25 19:13
I can't reproduce this issue. Everything seems to work as expected. It can be that this is already fixed by other commits as it is an old(er) ticket. Feel free to reopen if the problem still occurs.

**Closed by Michiel-s** 2016-07-25 19:13 UTC
Labels: bug, component:front-end, Current Sprint, priority:high
