### ISSUE TITLE
Specification of BOXes (interfaces, views) in relation with CRU(D)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#141] opened 2015-07-23 09:34 UTC
At (pretty much) any point (in an INTERFACE) where you have an atom (I refer to that as an 'anchorpoint' in this issue), At every such anchorpoint, precisely one 'Box' (which currently may be a BOX (incl. COLS, ROWS, etc.), a (LINKTO) INTERFACE, or an explicit or implicit VIEW) must be specified that defines the purpose/activity that can be done at such an anchorpoint. 

Since a [proposal for harmonizing the syntax of such 'Box'es](https://github.com/AmpersandTarski/ampersand/wiki/Interfaces,-Views-and-Violations-Syntax-Proposal) is already being discussed, I will use the term 'Box' to generically refer to such constructs. 

However, an anchorpoint should be useable for multiple, different purposes/activities. Currently, if a Box is specified for making things look good on the screen, you can use a VIEW with an HTML-template. However, if you want to update the atom at that same anchorpoint, you might want to display things in a different fashion, and allow editing in that VIEW. Similarly, the creation of an atom requires a VIEW to be different. Currently, an attempt to cope with this is made with $variables$ that are in the HTML template: one HTML template should fit all.

I would like to see it possible that a Box can be specified for a specific purpose. For starters, that would be CRU(D), but I can imagine other purposes (e.g. Select, or Compute an atom). This would mean that every anchorpoint should have at least one Box, each of which serves a specific purpose, and the interface/frontend engine must (somehow) select which one to use at what point in time.

The question I have is whether this is straightforward to implement (in which case this ticket is a feature request), or whether this needs discussion (in which case we might set up a wiki-page similar to the one mentioned above).

Note: this issue relates to #82 (Creation of new atoms), and may relate to #45 (CRUD in fspecs). 
Deze worden nu in alle gevallen gebruikt, en dat is onwenselijk. Het moet mogelijk worden om voor C, R en U specifieke interfaces te specificeren.

**Comment by Michiel-s** [comment] 2015-10-09 22:24
@RieksJ 
@stefjoosten 
@hanjoosten 
and others

I'm experimenting with having CRUD rights for interfaces. This post will describe my thoughts and implementation effort until now.

Currently, when specifying an INTERFACE in &, we can only explicitly specify the **Update** rights for relations for the **whole** interface. I think we need a more fine-grained approach on 2 dimensions:
1) be able to also explicitly specify Create, Read and Delete rights.
2) be able to specify those rights for all interface parts independently

I've implemented this feature in the zwolle frontend. All rights currently default to true. You can change this default config globally in the localSettings with the following codelines:
```
Config::set('defaultIfcForCreate', 'global', false);
Config::set('defaultIfcForRead', 'global', true);
Config::set('defaultIfcForUpdate', 'global', true);
Config::set('defaultIfcForDelete', 'global', false);
```
Please try this yourself to see the behavior in the frontend.

If CRUD rights are provided by Generics.php for all interface parts (not yet implemented) this will overwrite the default setting.

I propose to add **optional** CRUD syntax to the INTERFACE definition in the following way:
* after every expression in an interface definition the letters C, R, U, D can be provided
* capital letters mean that the operations are allowed, e.g.: `CRUD`
* non-capital letters mean that the operations are not allowed, e.g.: `crud`
* capital and non-capital letter may be used together, e.g.: `cRUd`
* C (CREATE) means that at that point a new atom of the tgt concept type can be created to populate the expression. Default: true
* R (READ) means that the expression may be read from the database. This looks trivial, but I already have use cases where you only want to be able to update expressions and not be able to read them. Default: true
* U (UPDATE) means that the expression can be updated. This means changing the tgt atom(s) of the expression (i.e. deleting and adding tuples (using existing atoms, otherwise you also require C rights). Default: false
* D (DELETE) means that the tgt atom can be deleted!  Default: false

An example of how such an INTERFACE definition could look like:
```
INTERFACE "Edit user" FOR "Admin" : I[User] cRUd
    ROWS [ "Username"      : userName U
	       , "Full name"     : userFullName U
	       , "Emailadres"    : userEmail U
	       , "Organization"  : userOrg cUd
	       , "Roles"         : userRole CRUd
	       ]
```
The example above illustrates that:
* With this interface a User atom can be read and updated.
* This interface cannot create and delete User atoms. This is already a nice feature, because it allows to limits the list of new atom interfaces that are presented in the UI
* The username, fullname and emailadres can be Created, Updated and Read (create and read are not specified but default to true)
* For the userOrg relation it is explicitly stated that create is not allowed, this means that only existing organization atoms can be used to populate this relation.

Looking forward to hear your suggestions, concerns and road blocks;)

Michiel

**Comment by hanjoosten** [comment] 2015-10-12 20:03
@Michiel-s , I just checked in a branch for this issue. Your wish is granted 8-)
I have only done some brief testing. Of course, you need to do the framework things yourself. I guess the Haskell part is correct. If not, let me know.

**Comment by Michiel-s** [comment] 2015-10-13 19:42
Hi Han, as we discussed today on the phone, I really like the changes so far. What still needs to be done is add the possibility to explicitly specify that a crud operation is **not** allowed by means of the lower capitals (as described in my earlier post). Furthermore we require those attributes (crudC, crudR,crudU and crudD also in the controller and view template generation.

**Comment by hanjoosten** [comment] 2015-10-13 19:46
I'm working on it just now...

**Comment by hanjoosten** [comment] 2015-10-13 21:50
This should be it. Let me know if you need anything else.

**Comment by RieksJ** [comment] 2015-10-25 17:01
I'm experimenting a bit with the WFLP (Resultdriven Processes) work. It seems to be a very nice start to something that may become much bigger. I propose that every BOX would also have such an optional CcRrUuDd specification. 

I am also pondering the use of specifying a relation (of which the source would be SESSION and the target would be the concept of the BOX-atom on which the CcRrUuDd specification works) that would be populated with the pair ('_SESSION', <createdatom>) whenever such an atom is created, and that would retunr the pair  ('_SESSION', <BOXatom>) when used within the Box (or perhaps also even outside the BOX?)

**Comment by hanjoosten** [comment] 2015-10-25 21:56
At the Haskell part, parsing the optional CcRrUuDd specification after the box expression is allready there. That is also passed to generics as far as I know. So it's up to @Michiel-s to make the magic happen 8-))

**Comment by Michiel-s** [comment] 2015-10-26 11:48
I agree

**Comment by Michiel-s** [comment] 2015-12-22 09:06
After each expression in an interface you will be able to specify CRUD rights. Capital = allowed, Non-capital = not allowed. When you leave out a letter, the default is used. See #253.
```
INTERFACE "ifc A" : expr CRUD
    BOX [ "label1" : expr cRUd
            , "label2" : expr C
            ]
```
The semantics for CRUD as we're implementing it right now are:

Operation | Tgt concept ISA Object | Tgt concept ISA Scalar
-------------|-------------------------------|------------------------------
C | Create new atom (concept = tgt of expr) and if expr is relation add link (src, new tgt) | **NA** *Warning: Not possible, use update*
R | Read allowed | Read allowed
U | Remove and/or add link (tuple src,tgt) from relation using existing tgt atoms. *When expr is not a relation -> Warning: Update not possible* | Remove and/or add link (tuple src,tgt) from relation. Tgt atom does not have to exists in & (= scalar). *When expr is not a relation -> Warning: Update not possible*
D | Delete atom (tgt) and all links where the atom is the src or tgt | **NA** *Warning: Not possible, use update*

**Comment by Michiel-s** [comment] 2016-02-12 14:52
Hi Han,

Could you implement the NA Warnings from the table above in branch #228 

Michiel

**Comment by hanjoosten** [comment] 2016-02-16 21:04
As discussed by phone, no distinction should be made based on the fact that an atom is Object or Scalar.

**Comment by Michiel-s** [comment] 2016-02-26 08:51
Fine by me, but I already warn you (and all Ampersand modelers) for unexpected behavior. Take for example this script:
```
quantity :: OrderLine * Nummertje
REPRESENT Nummertje TYPE INTEGER

INTERFACE "Edit orderline" : I [OrderLine]
  BOX [ "quantity" : quantity CRUD ]
```
When you perform a delete (D) on the quantity (e.g. atom 3 [Nummertje]) **all** links with atom 3 [Nummertje] as src or tgt will be removed.

I think this will cause unexpected behavior for the modelers, especially due to the choice that the default CRUD setting is to allow everything. But let's see how it goes.

**Comment by hanjoosten** [comment] 2019-01-02 15:40
As we can generate warnings while compiling an ampersand script, we can see if we can provide warnings for 'wrong' CRUD instructions provided by the user, as suggested by @Michiel-s in one of his comments above.

**Comment by Michiel-s** [comment] 2019-01-02 20:49
Duplicate of #745

**Closed by Michiel-s** 2019-01-02 20:49 UTC
Labels: Discussion, component:generating functional designs, component:global, component:html/js front-end, component:parser, component:prototype generator, enhancement
